### ISSUE TITLE
Database migration issues from old Airsonic

### ISSUE THREAD

**Issue by JulesCornelissen** [airsonic-advanced/airsonic-advanced#121]
## Problem description

I used to run Airsonic, but I want to try out Airsonic-advanced. I've always run Airsonic inside a Docker container, with the built in database. With Airsonic-advanced I've moved to MariaDB. After starting the DB and Airsonic-advanced container it starts to migrate the old database to MariaDB, this take a few minutes and then it's done. After it's done migrating, only the default admin user exists and none of the old users. The music data seems to be there, but the album thumbnail view in the middle is empty and if you try to click anything in the left side bar you get the following error:

```Status 	500
Error 	Internal Server Error
Message 	PreparedStatementCallback; SQL [insert into media_file (path, folder, type, format, title, album, artist, album_artist, disc_number, track_number, year, genre, bit_rate, variable_bit_rate, duration, file_size, width, height, cover_art_path, parent_path, play_count, last_played, comment, created, changed, last_scanned, children_last_updated, present, version, mb_release_id, mb_recording_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn=9) Duplicate entry '/var/music/somefolder/2017-05 - PURGE EP' for key 'idx_media_file_path'; nested exception is java.sql.SQLIntegrityConstraintViolationException: (conn=9) Duplicate entry '/var/music/somefolder/2017-05 - PURGE EP' for key 'idx_media_file_path'
Path 	/main.view
Time 	Sun Mar 08 16:51:58 GMT 2020
Exception 	
Java version 	AdoptOpenJDK 11.0.6
Operating system 	Linux 4.4.59+
Server 	Apache Tomcat/9.0.31
Memory 	Used 191 of 250 MB
Stack trace 	
                

                        org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [insert into media_file (path, folder, type, format, title, album, artist, album_artist, disc_number, track_number, year, genre, bit_rate, variable_bit_rate, duration, file_size, width, height, cover_art_path, parent_path, play_count, last_played, comment, created, changed, last_scanned, children_last_updated, present, version, mb_release_id, mb_recording_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; (conn=9) Duplicate entry '/var/music/somefolder/2017-05 - PURGE EP' for key 'idx_media_file_path'; nested exception is java.sql.SQLIntegrityConstraintViolationException: (conn=9) Duplicate entry '/var/music/somefolder/2017-05 - PURGE EP' for key 'idx_media_file_path'
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:243)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:927)
	at org.airsonic.player.dao.AbstractDao.update(AbstractDao.java:90)
	at org.airsonic.player.dao.MediaFileDao.createOrUpdateMediaFile_aroundBody0(MediaFileDao.java:193)
	at org.airsonic.player.dao.MediaFileDao$AjcClosure1.run(MediaFileDao.java:1)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:66)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:72)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:70)
	at org.airsonic.player.dao.MediaFileDao.createOrUpdateMediaFile(MediaFileDao.java:139)
	at org.airsonic.player.dao.MediaFileDao$$FastClassBySpringCGLIB$$15ad9359.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.airsonic.player.dao.MediaFileDao$$EnhancerBySpringCGLIB$$fcdf95f7.createOrUpdateMediaFile(<generated>)
	at org.airsonic.player.service.MediaFileService.lambda$9(MediaFileService.java:383)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(Unknown Source)
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.externalHelpComplete(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.tryExternalHelp(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.externalAwaitDone(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:390)
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:195)
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:174)
	at org.airsonic.player.controller.MainController.handleRequestInternal(MainController.java:91)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:62)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn=9) Duplicate entry '/var/music/somefolder/2017-05 - PURGE EP' for key 'idx_media_file_path'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:235)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:248)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:230)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:157)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:192)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$0(JdbcTemplate.java:867)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 159 more
Caused by: java.sql.SQLException: Duplicate entry '/var/music/somefolder/2017-05 - PURGE EP' for key 'idx_media_file_path'
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:289)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:221)
	... 165 more
```

### Steps to reproduce

1. Stop old Airsonic server
2. Copy over old Airsonic directory to new place
3. Create new DB container
4. Start Airsonic-Advanced with the old data
5. Wait for database migration to finish
6. Login with default credentials

## System information
 * **Airsonic version**: *the version listed on the About page*
Airsonic-advanced docker, latest version as of writing (10.6.0-SNAPSHOT.20200308063819)
 * **Operating system**: *the operating system you're running Airsonic on.
Linux, not sure which kernel, using Docker-Compose v3
   Linux, what distribution; Windows or Mac, what version?*
 * **Java version**: *the Java version you are using to run Airsonic.*
The one included in the Docker, seems to be AdoptOpenJDK 11.0.6
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* Behind a reverse proxy, same setup as old Airsonic.
 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*
Firefox 73.0.1
 * **Language**: *which langauge/internationalization is in use*
English

## Additional notes
If any additional information is needed please let me know.

**Comment by randomnicode** [comment]
Trying to get a better understanding here. That code block shouldn't be hitting if there's already an entry in the database for it; there is a very slight race condition (due to the old db version which we'll upgrade in 11.0 release), but it's pretty minor. I'm trying to clarify if this is a media scanning issue or a migration issue. I'm also trying to clarify how you're transferring data between two different DBs

So let's start from the beginning, please correct me where I have a misunderstanding:
- You were using the internal HSQLDB with Airsonic (in Docker). In Docker, you have the following volumes mapped:
  - You have your music mounted to `/airsonic/music`
  - You have your data (containing the DB) mounted to `/airsonic/data`
- Then you stopped your Airsonic container
- You bring up a MariaDB container
- You bring up an Airsonic-Advanced container
  - You have the MariaDB container _linked_ to Airsonic-Advanced so the containers can network and see each other
  - Your Airsonic-Advanced configuration options for the DB (url, user, pass, driver) now point to the MariaDB instance (how? via env vars? system properties? which properties?)
  - Your volumes are now mapped to:
    - You have your music mounted to `/var/music` (--> different from before)
    - You have your data (containing the old DB) mounted to `/var/airsonic` (--> different from before)

There are two questions:
- What are the env vars you're giving your container to connect to the MariaDB instance?
- How are you migrating from one DB (HSQLDB) to another (MariaDB)? Airsonic-Advanced (or Airsonic) currently provide no way to move data from one DB to another (it must be moved manually). If you point it to an empty MariaDB, it won't see the old data. If you point it to the old data, it won't see the new DB. You can't point it to two DBs. All documentation assumes you have a DB and continues using it (or start from scratch with a new DB). Thus, data migration from one DB to another must be done manually. (I'm trying to clarify this bit:  `it starts to migrate the old database to MariaDB`)

**Comment by JulesCornelissen** [comment]
Thanks for your reply! Let me get this out of the way first, so you do not have to read the rest of my reply.

>How are you migrating from one DB (HSQLDB) to another (MariaDB)? Airsonic-Advanced (or Airsonic) currently provide no way to move data from one DB to another (it must be moved manually). 

This is my mistake and what is probably leading to my issues, when I read the Airsonic documentation it mentions that it uses Liquibase for easy migration. I intereperted this as that it automatically migrates between databases (though I was confused how it knew, and how to trigger it). You can go ahead and close this issue if you want.

>Airsonic is built with generic ANSI SQL (for the most part) and uses Liquibase for database migrations [...]

This is completely my bad and I'm sorry for using up your time. I will however answer and clarify the rest of your post.

>You have your music mounted to /airsonic/music

I was using the Linuxserver.io Airsonic Docker before, which maps music at `/music` (and data at `/config`). Though this shouldn't matter much since both `/music` and `/airsonic/music` are different from Airsonic-Advanced's `/var/music`.

>Then you stopped your Airsonic container

Yes.

>You bring up a MariaDB container
>You bring up an Airsonic-Advanced container 

I setup a Docker-Compose as follows:
```version: '3'

networks:
  airsonic-advanced_network:
  
services:
  airsonic-advanced_db:
    image: mariadb:latest
    container_name: airsonic-advanced_db
    restart: unless-stopped
    networks:
      - airsonic-advanced_network
    volumes:
      - /volume1/docker/airsonic-advanced_db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_ROOT_PASSWORD=<Password>
      - MYSQL_PASSWORD=<Password>
      - MYSQL_DATABASE=<DB name>
      - MYSQL_USER=<DB user>
      
  airsonic-advanced:
    image: airsonicadvanced/airsonic-advanced:latest
    container_name: airsonic-advanced
    restart: unless-stopped
    ports:
      - port:4040
    networks:
      - airsonic-advanced_network
    depends_on:
      - airsonic-advanced_db
    volumes:
      - /volume1/docker/airsonic-advanced:/var/airsonic
      - /volume1/Music:/var/music
      - /volume1/Music/Playlists:/var/playlists
    environment:
      - tz=Europe/Amsterdam
```

My Airsonic-Advanced connects to the MariaDB instance using settings provided in airsonic.properties (in the root of the data folder)

```
DatabaseConfigType=embed
DatabaseConfigEmbedDriver=org.mariadb.jdbc.Driver
DatabaseConfigEmbedUrl=jdbc:mariadb://airsonic-advanced_db:3306/<DB name>
DatabaseConfigEmbedUsername=<DB user>
DatabaseConfigEmbedPassword=<Password>
```

Note: If you happen to want to test anything related to MariaDB currently and you want to start from scratch (i.e. have MariaDB init a new database) then take note of this particular issue: https://github.com/docker-library/mariadb/issues/262

You mention envs for the Airsonic-Advanced container to connect to the database, I am not aware of a way to do this? At least there seems to be nothing in the documentation that points to how to do this, it would make life easier when creating a new install of Airsonic-Advanced instead of having to specifiy it in a properties file.

>Thus, data migration from one DB to another must be done manually.
As mentioned above I didn't realise this, when I get the time I will try to do a manual migration and see if that works. I am however still confused as to why it is able to still see all the indexed files though, but maybe this is also read somewhere else..?

I believe this should answer your questions, if there's anything else you're curious about let me know. Thanks again and once again sorry for taking up your time with my mistake.

**Comment by randomnicode** [comment]
> This is my mistake and what is probably leading to my issues

No worries, not an issue at all. I'll answer some of your questions and offer suggestions, hopefully it'll help get you up and running.

```
 command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
```
You should use the `utf8mb4` charset (the default), unless you have a specific reason to use `utf8`. Similarly, the collation you have is case insensitive (`ci` part in the name), which means it can't tell the difference between data like Admin and admin. You might want a case sensitive collation, like `utf8mb4_bin`. Here is airsonic-advanced's travis setting up the db to do it's automated testing: https://github.com/airsonic-advanced/airsonic-advanced/blob/master/.travis.yml#L83


>You mention envs for the Airsonic-Advanced container to connect to the database, I am not aware of a way to do this? At least there seems to be nothing in the documentation that points to how to do this, it would make life easier when creating a new install of Airsonic-Advanced instead of having to specifiy it in a properties file.

Ah yes, Airsonic-Advanced can actually read from the environment (and even the jvm system properties) also instead of just the properties file (unlike Airsonic). So you can specify most config options via the environment also for Airsonic-Advanced. That's actually how the travis CI/CD testing is set up for external DBs.

Try addinig all the config vars to your environment instead of your properties file
```
    environment:
      - tz=Europe/Amsterdam
      - DatabaseConfigType=embed
      - DatabaseConfigEmbedDriver=org.mariadb.jdbc.Driver
      - DatabaseConfigEmbedUrl=jdbc:mariadb://airsonic-advanced_db:3306/<DB name>
      - DatabaseConfigEmbedUsername=<DB user>
      - DatabaseConfigEmbedPassword=<Password>
```

That should get the system to pick it up automatically.

Make sure your properties file doesn't have these properties. I think if both env and properties files carry the same property, then the properties file takes precedence (I'd have to check to be sure, or you can experiment).

**Comment by randomnicode** [comment]
> Note: If you happen to want to test anything related to MariaDB currently and you want to start from scratch (i.e. have MariaDB init a new database) then take note of this particular issue: docker-library/mariadb#262

Thanks for the heads up!

**Comment by randomnicode** [comment]
> . I intereperted this as that it automatically migrates between databases (though I was confused how it knew, and how to trigger it)

This is an interesting use case, and perhaps a feature enhancement: migrate Airsonic's internal DB to an external one.

**Comment by dorel14** [comment]
Hello 
I've tested to make the same when migrating from subsonic to airsonic and at same time migrate from hsqldb => postgres en made it with a talend jobs

https://fr.talend.com/products/data-integration/

But perhaps somethong can be made directly in java

**Comment by randomnicode** [comment]
Going to close this issue as it seems to have been resolved. Feel free to reopen or open a new one for another issue.
