### ISSUE TITLE
Can't run/debug Airsonic-Advanced with IntelliJ

### ISSUE THREAD

**Issue by Faeb35** [airsonic-advanced/airsonic-advanced#251]
## Problem description

Hi buddies,
I would like start to contribute to Airsonic-Advanced (I'm quit a beginner, so don't expect to much). To do that I followed these instructions to build and run/debug Airsonic-Advanced.
https://airsonic.github.io/docs/developer/intellij/#use-embedded-spring-boot
I can run Airsonic -> Lifecycle -> package and this finishes without any error, but some warnings. So all good so far. But when I start the run/debug config "Application" I'm getting the following error. Something seems to be wrong with my Spring Boot config, but I can't figure out what it is.

```
Java HotSpot(TM) 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
15:39:56.672 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: unknown
15:39:56.691 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.ExceptionInInitializerError: null
	at org.airsonic.player.service.SettingsService.<clinit>(SettingsService.java:155)
	at org.airsonic.player.spring.LoggingFileOverrideListener.onApplicationEvent(LoggingFileOverrideListener.java:20)
	at org.airsonic.player.spring.LoggingFileOverrideListener.onApplicationEvent(LoggingFileOverrideListener.java:15)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140)
	at org.airsonic.player.Application.main(Application.java:81)
Caused by: javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:116)
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:47)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolator(ConfigurationImpl.java:474)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(ConfigurationImpl.java:650)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.getMessageInterpolator(ConfigurationImpl.java:397)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:183)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:364)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at org.airsonic.player.util.Util.<clinit>(Util.java:202)
	... 13 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/el/ELManager
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:108)
	... 22 common frames omitted

Process finished with exit code 1
```

I also tried to build and run the vanilla Airsonic. There I was sucessfull.

What can I do to get over this? What did I miss?

## System information

 * **Airsonic version**: Edge Release 10.6.0-SNAPSHOT.20200424035525
 * **Operating system**: Windows 10
 * **Java version**: jdk-14.0.1
 * **IntelliJ version**: 2020.1

**Comment by Faeb35** [comment]
After hours of trying to get it working... just after submiting this issue... it fixed by myself:
I had to re-enable the 'Include dependencies with "Provided" scope' in the Spring Boot Application configuration. The documentations about vanilla Airsonic stats, that this should be disabled, for Airsonic-Advanced it seems to be necessary to be enabled.
