### ISSUE TITLE
Playlist do not get imported automatically

### ISSUE THREAD

**Issue by sandersantema** [airsonic-advanced/airsonic-advanced#324]
## Problem description
I've got a folder setup where I export playlists to from iTunes to import automatically, however this doesn't work. I've configured this under general -> Import Playlists From. There's nothing wrong with the format, manually importing works and I've configured my playlist export script to mirror the path format of playlists created in AirSonic.

### Steps to reproduce
1. Enable playlist auto import
2. Nothing is imported

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20200603112807 
 * **Operating system**: MacOS 10.13 I believe, I imported the playlist manually (with a file copied from my Mac Mini) on my Linux machine. 
* **Java Version**:  java 14.0.1

**Comment by sandersantema** [comment]
It weirdly enough it seems like it just updated out of the blue after scanning my media folders manually. It still doesn't seem to be happening manually however.

**Comment by Rudd-O** [comment]
I still have this problem and manual scans do not help.

**Comment by sandersantema** [comment]
> I still have this problem and manual scans do not help.

Have you looked into the format of the playlists you're trying to import? I don't think that would fix it completely either but it's one problem less.

**Comment by SyntrophicConsortium** [comment]
How often are they imported? I added an .m3u file with valid file paths in it to the playlist path specified in the settings and it hasn't imported. It's been 24 hours. I didn't see anything in the logs. There should be a manual import option and/or a way to trigger scanning for playlists, as you can do for the media library.

**Comment by randomnicode** [comment]
Playlists should be scanned and imported at least every time the media library is scanned?

**Comment by Rudd-O** [comment]
I've completed a manual scan.  No playlists imported.  Latest EDGE release.

I have a strong preference not to give my opinion on what I actually think about this backtrace:

```
2021-02-11 10:41:09.069  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /srv/shared/Entertainment/Music/Playlists

java.io.IOException: Is a directory
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_275]
	at sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:46) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_275]
	at sun.nio.ch.IOUtil.read(IOUtil.java:197) ~[na:1.8.0_275]
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:159) ~[na:1.8.0_275]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65) ~[na:1.8.0_275]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:109) ~[na:1.8.0_275]
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103) ~[na:1.8.0_275]
	at java.io.InputStream.read(InputStream.java:101) ~[na:1.8.0_275]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314) ~[commons-io-2.6.jar!/:2.6]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270) ~[commons-io-2.6.jar!/:2.6]
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291) ~[commons-io-2.6.jar!/:2.6]
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246) ~[commons-io-2.6.jar!/:2.6]
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:765) ~[commons-io-2.6.jar!/:2.6]
	at chameleon.playlist.SpecificPlaylistFactory.readFrom(SpecificPlaylistFactory.java:131) ~[core-1.2.1-RELEASE.jar!/:na]
	at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:237) ~[classes!/:10.6.0]
	at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:352) ~[classes!/:10.6.0]
	at org.airsonic.player.service.PlaylistService.lambda$15(PlaylistService.java:329) ~[classes!/:10.6.0]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:1.8.0_275]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_275]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_275]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_275]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_275]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_275]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:1.8.0_275]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:1.8.0_275]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_275]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[na:1.8.0_275]
	at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:327) ~[classes!/:10.6.0]
	at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:308) ~[classes!/:10.6.0]
	at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:195) ~[classes!/:10.6.0]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[na:1.8.0_275]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[na:1.8.0_275]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) ~[na:1.8.0_275]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_275]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_275]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_275]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[na:1.8.0_275]

2021-02-11 10:41:09.075  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
```

**Comment by Rudd-O** [comment]
EDIT to add: How TF is THIS code:

```
        List<Playlist> allPlaylists = playlistDao.getAllPlaylists();
        try (Stream<Path> children = Files.walk(playlistFolder)) {
            children.filter(f -> Files.isRegularFile(f) && Files.isReadable(f)).forEach(f -> {
                try {
                    importPlaylistIfUpdated(f, allPlaylists);
                } catch (Exception x) {
                    LOG.warn("Failed to auto-import playlist {}", f, x);
                }
            });
        } catch (IOException ex) {
            LOG.warn("Error while reading directory {} when importing playlists", playlistFolder, ex);
        }
```

yielding an iterator that says *a directory* matches the expression there?

**Comment by Rudd-O** [comment]
Might be my fault.  ^^ It looks like my system installed Airsonic Advanced 10 instead of 11.  Trying with actual latest WAR.

**Comment by Rudd-O** [comment]
Goddamn RPM.

**Comment by Rudd-O** [comment]
Latest code no dice, different traceback:

```
Feb 11 11:33:58 penny.dragonfear java[1317763]: 2021-02-11 11:33:58.377  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /srv/shared/Entertainment/Music/Playlists/2008-09 and 2008-10.m3u
Feb 11 11:33:58 penny.dragonfear java[1317763]: java.lang.Exception: Unsupported playlist 2008-09 and 2008-10.m3u
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:239) ~[classes!/:11.0.0-SNAPSHOT]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:352) ~[classes!/:11.0.0-SNAPSHOT]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at org.airsonic.player.service.PlaylistService.lambda$15(PlaylistService.java:329) ~[classes!/:11.0.0-SNAPSHOT]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:327) ~[classes!/:11.0.0-SNAPSHOT]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:308) ~[classes!/:11.0.0-SNAPSHOT]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:195) ~[classes!/:11.0.0-SNAPSHOT]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
Feb 11 11:33:58 penny.dragonfear java[1317763]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

**Comment by Rudd-O** [comment]
What does it mean "unsupported playlist"?

**Comment by Rudd-O** [comment]
Can't get debug logging to enable for `chameleon` no matter how I try, not even through https://airsonic.github.io/docs/logging/ .

Chameleon is broken -- it won't import trivial M3U files.

**Comment by Rudd-O** [comment]
Tried with an XSPF playlist:

```
2021-02-11 12:38:53.192  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /srv/shared/Entertainment/Music/Playlists/2020-12.xspf

java.lang.Exception: Unsupported playlist 2020-12.xspf
	at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:239) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:352) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.lambda$15(PlaylistService.java:329) ~[classes!/:11.0.0-SNAPSHOT]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:327) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:308) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:195) ~[classes!/:11.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

Something about the Chameleon code this app is calling is rotten — no Chameleon providers are in fact loaded at all, so the Playlist factory keeps returning `NULL`.

Please fix this.

**Comment by yllekz** [comment]
I think I'm also experiencing this. I am pointed at my playlists folder, and it appeared to work one time, at random. I created more playlists files since then (I guarantee the paths are correct) but Airsonic won't find them even if manually scanning.

**Comment by johnmurrayvi** [comment]
I'm having the exact same issue.
While on the latest release, I exported playlists from Airsonic to create a fresh database, as I had the same problem as #491. 
With a fresh database, on the latest release, the same version that I exported the playlists from, Airsonic will not import the playlists it exported. This occurs when attempting to import a single playlist manually as well as through the media scan. I've tried m3us, the m3u8s that Airsonic exported, and xspf versions. Nothing works.

Every log entry for the failed import has the format as mentioned [above](https://github.com/airsonic-advanced/airsonic-advanced/issues/324#issuecomment-777426244):
```
java.lang.Exception: Unsupported playlist <playlist file name>
	at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:239) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:352) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.lambda$15(PlaylistService.java:329) ~[classes!/:11.0.0-SNAPSHOT]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
	at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:327) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:308) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:195) ~[classes!/:11.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

**Comment by yllekz** [comment]
I have a small update...I was able to get around this via a very small detail that took me quite some time to realize. It seems Airsonic is heavily sensitive to casings in m3u playlists, and if the paths don't line up exactly, I would get errors in the console similar to others above, and the playlists would not show up. It wasn't until hours of desperate banging my head against the wall when I realize that if I meticulously observed the path casings, the problem went away for me and playlists were able to import again.

So I guess the takeaway is, perhaps there could be room for adjusting the case-sensitivity in playlists, or adjust Airsonic's code to automatically convert the text contents of m3u files to lower case to avoid this entirely.

**Comment by uSlackr** [comment]
That’s a Linux thing.  Case-sensitive by default.

\\Greg

**Comment by johnmurrayvi** [comment]
I can confirm that this _**is**_ an issue with the WAR packaging. 

After finding the post by @Rudd-O [here](https://github.com/airsonic-advanced/airsonic-advanced/issues/331#issuecomment-777470740), from #331, I extracted the WAR file and followed what the docker scripts do.

I updated my airsonic.service unit for systemd and automatic playlist import _instantly_ started working upon restarting the the service. It picked up all of the playlists in the directories I already had configured, that refused to import, while running with the WAR file.

I'm not running through docker, so I'm stuck with the WAR file and doing this manually every update, I guess.

**Comment by randomnicode** [comment]
This is indeed a chameleon issue. It's not using the correct classloader to pull in the implementations via the service loading mechanism.

#539 should fix this issue

**Comment by randomnicode** [comment]
@Rudd-O , @johnmurrayvi Please verify the fix works?

**Comment by johnmurrayvi** [comment]
Seems like it's working for me!
You're my hero right now, I sincerely appreciate it.

**Comment by yourfavoriteweapon** [comment]
I am having this same issue.  How do you apply the update you posted? I am using this in an unraid docker and it isn't showing an update is available.

**Comment by randomnicode** [comment]
airsonic-advanced CD pipeline releases a plain docker image after every merge, which you may run. The images are available here: https://hub.docker.com/r/airsonicadvanced/airsonic-advanced (just look for the latest tag and that'll get the most updated version)
