### ISSUE TITLE
NPE On Login Page (Fresh airsonic [vanilla] migration)

### ISSUE THREAD

**Issue by mcrosson** [airsonic-advanced/airsonic-advanced#354]
## Problem description

Upon first running airsonic advanced with pre-existing data from an airsonic deployment I get a null pointer exception when the login page is shown.

My intent is to migrate from airsonic to airsonic advanced. I checked the migrated hsql database with Dbeaver and it showed 2 rows with empty credential records which I removed as part of the troubleshooting process. Removing these 2 records did not prevent the crash.

### Steps to reproduce

- Run original airsonic service
- Use it heavily for just over a year
- Discover airsonic advanced
- Shutdown original airsonic instance
- Copy original airsonic data to new location
- Run airsonic advanced with the original data and let it complete database migrations
- Attempt to login to airsonic advanced

## System information

Original airsonic release : ```10.6.2-RELEASE – May 3, 2020```
Airsonic advanced release : ```docker hub release as of 2020-07-22 @ 18:57 EST (UTC-4)```

## Additional notes

Stack trace

```

2020-07-22 22:50:10.096 DEBUG --- o.s.web.servlet.view.JstlView            : View name 'error', model {timestamp=Wed Jul 22 22:50:10 UTC 2020, status=500, error=Internal Server Error, message=No message available, trace=java.lang.NullPointerException
        at org.airsonic.player.service.SecurityService.lambda$6(SecurityService.java:177)
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(Unknown Source)
        at java.base/java.util.stream.MatchOps$MatchTask.doLeaf(Unknown Source)
        at java.base/java.util.stream.AbstractShortCircuitTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
        at org.airsonic.player.service.SecurityService.checkDefaultAdminCredsPresent(SecurityService.java:177)
        at org.airsonic.player.controller.LoginController.login(LoginController.java:53)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:59)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:56)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

```

**Comment by mcrosson** [comment]
Looks like the user_credentials app field needs to have a value of 'Airsonic' instead of the 'AIRSONIC' that was populated as part of the migration.

This no longer applies.

**Comment by randomnicode** [comment]
Hi

> Looks like the user_credentials app field needs to have a value of 'Airsonic' instead of the 'AIRSONIC' that was populated as part of the migration.

This is incorrect.

The migration applies `AIRSONIC`, which is the UserCredential.App enum, as seen here: https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/resources/liquibase/10.6/user-credentials.xml#L41

The application also expects and needs the enum (`AIRSONIC`) when reading from the DB and NOT the display name (`Airsonic`):
https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java#L100
https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java#L128
https://github.com/airsonic-advanced/airsonic-advanced/blob/master/airsonic-main/src/main/java/org/airsonic/player/dao/UserDao.java#L261

I suspect you're doing some manual manipulation of your db?
`Airsonic` won't be understood by the application, so if you've made that change, you should revert it.

**Comment by mcrosson** [comment]
I was doing some manual db manipulations as part of moving away from hsql -> postgres

I managed to discover that it was something funny with my migration script and once I spent a little time with the hsql 'data' I was able to get airsonic-advanced deployed with my old hsql data and it's up and running great.

👍
