### ISSUE TITLE
Cannot upgrade from 10.6 to EDGE on Tomcat

### ISSUE THREAD

**Issue by nowheretobefound** [airsonic-advanced/airsonic-advanced#396]
## Problem description

` tail -f airsonic.log -n 100
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.36]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[na:na]
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[catalina.jar:9.0.36]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.36]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633) ~[catalina.jar:9.0.36]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343) ~[bootstrap.jar:9.0.36]
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474) ~[bootstrap.jar:9.0.36]

2020-10-15 21:57:42.307  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /var/airsonic/db.backup.20201015215742
2020-10-15 21:57:42.325 ERROR --- o.s.boot.SpringApplication               : Application run failed

java.lang.RuntimeException: Failed to upgrade HSQLDB database
        at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:160) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:17) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:1) ~[classes/:11.0.0-SNAPSHOT]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.springframework.boot.context.event.EventPublishingRunListener.contextPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:59) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:371) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:152) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:132) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:92) ~[spring-boot-2.2.10.RELEASE.jar:2.2.10.RELEASE]
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848) ~[catalina.jar:9.0.36]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.36]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[na:na]
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[catalina.jar:9.0.36]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-util.jar:9.0.36]
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[catalina.jar:9.0.36]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[catalina.jar:9.0.36]
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633) ~[catalina.jar:9.0.36]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343) ~[bootstrap.jar:9.0.36]
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474) ~[bootstrap.jar:9.0.36]
Caused by: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:file:/var/airsonic/db/airsonic;hsqldb.tx=mvcc;sql.enforce_size=false;sql.char_literal=false;sql.nulls_first=false;hsqldb.defrag_limit=50;shutdown=true
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702) ~[java.sql:na]
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189) ~[java.sql:na]
        at org.airsonic.player.util.LegacyHsqlMigrationUtil.getHsqlDbConnection(LegacyHsqlMigrationUtil.java:45) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.util.LegacyHsqlMigrationUtil.performHsqlDbUpgrade(LegacyHsqlMigrationUtil.java:123) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:157) ~[classes/:11.0.0-SNAPSHOT]
        ... 54 common frames omitted

`

### Steps to reproduce
Upgrading from 10.6 to EDGE on tomcat and you get driver not found.
Same issue as JPSONIC issue #521
## System information

 * **Airsonic version**: *11 something*
 * **Operating system**: *OpenSuse 15.2*
 * **Java version**: *11*
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* None
 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*
 * **Language**: *which langauge/internationalization is in use*

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by randomnicode** [comment]
Would like to know:
- Which EDGE snapshot?

If you can point out the exact war, that would help a bunch

**Comment by nowheretobefound** [comment]
https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20201007202626

**Comment by nowheretobefound** [comment]
Guess its the same as this : https://github.com/tesshucom/jpsonic/issues/521

**Comment by nowheretobefound** [comment]
Got it to boot by putting the hsql-db.jar into tomcat/lib folder and then it upgraded the db , but still get this :


java.sql.SQLException: No suitable driver
        at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:na]
        at org.airsonic.player.util.LegacyHsqlMigrationUtil.isHsqlDbBackupNeeded(LegacyHsqlMigrationUtil.java:72) ~[classes/:11.0.0-SNAPSHOT]

So it creates a new db backup on every boot, which kinda eat disk space

**Comment by randomnicode** [comment]
which tomcat are you using?
do you have other apps deployed on the tomcat that use the db?

**Comment by nowheretobefound** [comment]
OpenSuse Leap 15.2 Tomcat Version 9.0.36. No other apps deployed.

**Comment by nelsongt** [comment]
Hello I have same problem on FreeBSD 11.4.  First I tried tomcat10 with openjdk11 but with tomcat10 I cannot get airsonic-advanced to start or show any logs for some reason. Rather then investigate I moved to tomcat9 which starts airsonic-advanced 11 snapshot but I got "No suitable driver found" related to hsqldb error as above. Copying hsqldb.jar to tomcat lib folder allows airsonic to run but I probably have same problem with db backup but I have not checked this out yet since I rarely reboot my server.

For anyone else interested in BSD installation with tomcat here are steps to reproduce working airsonic snapshot:

Follow guide from here except I use tomcat9 instead of tomcat85: https://airsonic.github.io/docs/install/example/freebsd-freenas/
Extra steps:
During pkg install command add two targets:
`pkg install tomcat9 nano openjdk11 hsqldb`
Add extra line to rc_conf:
`tomcat9_java_home="/usr/local/openjdk11"`
Finally copy or symlink hsqldb.jar to tomcat lib folder:
`cp /usr/local/share/java/classes/hsqldb.jar /usr/local/apache-tomcat-9.0/lib/`

Hope this is helpful
