### ISSUE TITLE
Not a bug jsut some help 

### ISSUE THREAD

**Issue by dorel14** [airsonic-advanced/airsonic-advanced#402]
## Problem description

Can someone help me how to configure to permit accented name in folders and files
For example "Usher feat. Tego Calder��n" => "Usher feat. Tego Calderón"

my locales are set in utf8
~~~
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
~~~
And tried this in my systemd file
~~~
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.context-path=${CONTEXT_PATH} \
          -Dserver.address=127.0.0.1 \
          -Dserver.port=${PORT} \
          -DLC_CTYPE=UTF-8 \
          -Dfile.encoding=UTF-8 \
          -Dsun.jnu.encoding=UTF-8\
          -jar ${JAVA_JAR} $JAVA_ARGS

~~~

### Steps to reproduce

Create a folder like  "Usher feat. Tego Calderón" with some medias inside and launch a scan 

## System information

 * **Airsonic version**: *11.0.0-SNAPSHOT.20201002122917
 * **Operating system**: *Debian 9

 * **Java version**: *openjdk 11.0.6 2020-01-14
 * **Proxy server**: *Nginx
 * **Client**: *Chrome
 * **Language**: *French

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*
my logs 
~~~
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /var/music/Usher feat. Tego Calder��n
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:145) ~[na:na]
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279) ~[na:na]
        at java.base/java.nio.file.Path.of(Path.java:147) ~[na:na]
        at java.base/java.nio.file.Paths.get(Paths.java:69) ~[na:na]
        at org.airsonic.player.domain.MediaFile.getFile(MediaFile.java:141) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.domain.MediaFile.getParentFile(MediaFile.java:322) ~[classes!/:11.0.0-SNAPSHOT]
        at jdk.internal.reflect.GeneratedMethodAccessor381.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:688) ~[jackson-databind-2.10.5.jar!/:2.10.5]
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722) ~[jackson-databind-2.10.5.jar!/:2.10.5]
        ... 48 common frames omitted
~~~

**Comment by dorel14** [comment]
My airsonic is working strange 
When i launch with a systemd file, my left.vie is missing and i have a lot of errors in logs like describe before
~~~
[Unit]
Description=Airsonic Media Server
After=remote-fs.target network.target
AssertPathExists=/var/airsonic

[Service]
Type=simple
Environment="JAVA_JAR=/var/airsonic/airsonic.war"
Environment="JAVA_OPTS=-Xmx512m"
Environment="AIRSONIC_HOME=/var/airsonic"
Environment="PORT=4040"
Environment="CONTEXT_PATH=/"
Environment="JAVA_ARGS="
EnvironmentFile=-/etc/default/airsonic
ExecStart=/usr/bin/java \
          $JAVA_OPTS \
          -Dairsonic.home=${AIRSONIC_HOME} \
          -Dserver.servlet.contextPath=${CONTEXT_PATH} \
          -Dserver.port=${PORT} \
          -jar ${JAVA_JAR} $JAVA_ARGS
User=airsonic
Group=airsonic

# See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
# for details
DevicePolicy=closed
DeviceAllow=char-alsa rw
NoNewPrivileges=yes
PrivateTmp=yes
PrivateUsers=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallFilter=~@clock @debug @module @mount @obsolete @privileged @reboot @setuid @swap
ReadWritePaths=/var/airsonic

# You can uncomment the following line if you're not using the jukebox
# This will prevent airsonic from accessing any real (physical) devices
#PrivateDevices=yes

# You can change the following line to `strict` instead of `full`
# if you don't want airsonic to be able to
# write anything on your filesystem outside of AIRSONIC_HOME.
ProtectSystem=full

# You can uncomment the following line if you don't have any media
# in /home/…. This will prevent airsonic from ever reading/writing anything there.
#ProtectHome=true

# You can uncomment the following line if you're not using the OpenJDK.
# This will prevent processes from having a memory zone that is both writeable
# and executeable, making hacker's lifes a bit harder.
#MemoryDenyWriteExecute=yes


[Install]
WantedBy=multi-user.target
~~~
when i take the command line , everything is fine 
~~~
/usr/bin/java -Xmx512m -Dairsonic.home=/var/airsonic -Dserver.context-path=/ -Dserver.address=127.0.0.1 -Dserver.port=4040 -jar /var/airsonic/airsonic.war
~~~

**Comment by cascooscuro** [comment]
Have you tried to reconfigure locales?:
```
dpkg-reconfigure locales
localectl set-locale LANG=fr_FR.UTF-8 LANGUAGE=fr_FR.UTF-8
```

**Comment by dorel14** [comment]
Hello
I've tried the command "localectl set-locale LANG=fr_FR.UTF-8 LANGUAGE=fr_FR.UTF-8"  and now everything os ok ..
Big thx
