### ISSUE TITLE
Java version requirements?

### ISSUE THREAD

**Issue by JannesMeyer** [airsonic-advanced/airsonic-advanced#408]
## Problem description

I am a bit puzzled over what is the minimum Java version required to run Airsonic Advanced.

The README seems to say that any 1.8.x JRE is fine:

> You need a minimum Java Runtime Environment (JRE) of 1.8 for 10.6.x series and 11 for 11.x onwards (including snapshots). It is run similarly to (and in lieu of) vanilla Airsonic.

However, when I try to run Airsonic Advanced I get this error:

```
$ java -jar airsonic.war
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/airsonic/player/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:58)
```

Searching for that error message I found some people saying that I might need Java 9, but then why does the README say that Java 8 is the minimum?

The latest version of Vanilla Airsonic works fine, by the way.

Here is my output for `java -version`:

```
$ java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
```

Unfortunately, Java 9 is not supported by Synology Linux yet, so that's why I am stuck on Java 8 for now.

## System information

 * **Airsonic version**: Edge Release 11.0.0-SNAPSHOT.20201007202626
 * **Operating system**: Synology Linux 6.2.3-25426
 * **Java version**: 1.8.0_271
 * **Proxy server**: None
 * **Client**: Firefox 83
 * **Language**: en-US

**Comment by randomnicode** [comment]
Your details mention that you are running this version of Airsonic-Advanced:
> Airsonic version: Edge Release 11.0.0-SNAPSHOT.20201007202626

which is an 11.x release, which according to the README note you posted yourself, requires at least Java *11*:

> You need a minimum Java Runtime Environment (JRE) of 1.8 for 10.6.x series and 11 for 11.x onwards (including snapshots). It is run similarly to (and in lieu of) vanilla Airsonic.


In short, I think you misread the note:
For 10.6.x releases -> Java 8
For 11.x releases and onwards -> Java 11

I don't know about Synology, but Java 8 has reached EOL and Java 11 is now the current LTS release
