### ISSUE TITLE
Shared album link response 500 Internal Server Error

### ISSUE THREAD

**Issue by ReinforceZwei** [airsonic-advanced/airsonic-advanced#424]
## Problem description

The share link responses with 500 Internal Server Error after clicking it.
![image](https://user-images.githubusercontent.com/39955851/104272928-25939f00-54d9-11eb-8f01-c7e131970dd3.png)

![image](https://user-images.githubusercontent.com/39955851/104273092-625f9600-54d9-11eb-9a26-d154e4632031.png)

### Steps to reproduce

1. Create a share link by clicking the share button
![image](https://user-images.githubusercontent.com/39955851/104273300-9b980600-54d9-11eb-9d87-a5d3ed0ed59c.png)
2. A sharable link will be created. Click on it.
3. A response with 500 Internal Server Error will be returned.

## System information

 * **Airsonic version**: 10.6.0.20200424173747
 * **Operating system**: Raspbian Buster
 * **Java version**: Raspbian 11.0.3
 * **Proxy server**: nginx (I have tried visit the link with direct IP but still the same response)
 * **Client**: Chrome 87
 * **Language**: English

## Additional notes

Stack trace
```
java.lang.NullPointerException
	at com.auth0.jwt.TokenUtils.splitToken(TokenUtils.java:15)
	at com.auth0.jwt.JWTDecoder.<init>(JWTDecoder.java:34)
	at com.auth0.jwt.JWTVerifier.verify(JWTVerifier.java:246)
	at org.airsonic.player.service.JWTSecurityService.verify(JWTSecurityService.java:82)
	at org.airsonic.player.service.JWTSecurityService.verify(JWTSecurityService.java:86)
	at org.airsonic.player.controller.ExternalPlayerController.getSongs(ExternalPlayerController.java:107)
	at org.airsonic.player.controller.ExternalPlayerController.handleRequestInternal(ExternalPlayerController.java:98)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:95)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by randomnicode** [comment]
seems like a jwt parsing error, are you sure you added the complete jwt to the url query?

try copy pasting the jwt to this website and see what it says:
https://jwt.io/

note: the jwt is everything after jwt= (starting with eyJ)

**Comment by ReinforceZwei** [comment]
The jwt looks good.
![image](https://user-images.githubusercontent.com/39955851/105259171-3c677f00-5bc6-11eb-8ef4-99b920365ab3.png)

**Comment by randomnicode** [comment]
Only reason there'd be an NPE there would be if there was no token, I'm not sure your token is getting to the server

**Comment by ReinforceZwei** [comment]
I tested with cURL and not going through the proxy server, it still gives me the same result.
![image](https://user-images.githubusercontent.com/39955851/105351611-bd0a9780-5c27-11eb-87e1-99d9f989ab37.png)

**Comment by randomnicode** [comment]
Hmmm, like I said, for some reason your jwt token in the query param isn't passing through:

- If you run your program with the `--debug` argument, what do you get on the server side for the corresponding request (`java -jar -D... airsonic.war --debug`)? Do you see something similar to the following?
```
2021-01-21 06:11:10.128 DEBUG --- o.s.w.servlet.DispatcherServlet          : GET "/airsonic/ext/share/JWVGA?jwt=eyJ0....", parameters={masked}
```

- Your airsonic version is very old. Perhaps you should upgrade and try with a newer version in the 11.x series

**Comment by ReinforceZwei** [comment]
I haven't enable debug mode and I already saw the full jwt token in the airsonic log file. So seems like airsonic is getting the full token.
![image](https://user-images.githubusercontent.com/39955851/105366350-33b09080-5c3a-11eb-861d-61d4ec79533d.png)
```
2021-01-21 20:26:29.010 ERROR --- o.a.p.s.LoggingExceptionResolver         : 192.168.1.102: An exception occurred while loading http://192.168.1.29:8800/music/ext/share/JWVGA?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm9ueW1vdXMiLCJwYXRoIjoiL211c2ljL2V4dC9zaGFyZS9KV1ZHQSIsImlzcyI6ImFpcnNvbmljIiwiZXhwIjoxNjQyNzQ3MzA3fQ.njjGmbSJQ46gGBV9GOv40hKNmMEE2fNVoDR7ZwIxkqg

java.lang.NullPointerException: null
        at com.auth0.jwt.TokenUtils.splitToken(TokenUtils.java:15) ~[java-jwt-3.10.0.jar!/:3.10.0]
...
```

> Your airsonic version is very old. Perhaps you should upgrade and try with a newer version in the 11.x series

I am using the latest stable release from [github release](https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/v10.6.0). Actually I am waiting for the release of 11.x. Maybe I will upgrade to 11.x at some point and hopefully the problem will be resolved.

Anyway, thanks for your help. I will close this issue for now.

**Comment by randomnicode** [comment]
The 11.x snapshots are pretty stable. Just pick the latest.

You could also try deleting your jwt key and inputting a new one, then recreating the share

**Comment by ReinforceZwei** [comment]
After I changed the jwt key, the 500 error message is changed to something like `Invalid Signature` (I didn't take the screenshot)
So I restarted airsonic and tried again. The error message went back to `NullPointerException`.

I think I will just give-up fixing this function on 10.x, as I rarely share album, and put my eyes on 11.x.

**Comment by randomnicode** [comment]
> After I changed the jwt key, the 500 error message is changed to something like Invalid Signature (I didn't take the screenshot)

Yup, that's expected. You need to share again, the old share won't work because the jwt token is no longer valid (you changed the key). 1. Change the key, 2. Reshare, 3. See if the new share works.

> I think I will just give-up fixing this function on 10.x, as I rarely share album, and put my eyes on 11.x.

Okay, you can grab the latest 11.x snapshot binary from the releases page, it's pretty stable.
