### ISSUE TITLE
out of memory - heap space during scanning large library

### ISSUE THREAD

**Issue by mamema** [airsonic-advanced/airsonic-advanced#495]
## Problem description
scanning large library >80.000 files leads to 

Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space

using latest docker image.
The host has 32 GB, so i gues i need to change heap moemory, but didn't find config options.....

**Comment by randomnicode** [comment]
provide JAVA_OPTS env var to the container with the appropriate args to the jvm

`JAVA_OPTS=-Xmx1024m`

**Comment by randomnicode** [comment]
Make sure you give your Docker system and container enough memory

**Comment by 3Dscrewer** [comment]
@mamema In my case, stand-alone configuration as described at original Airsonic doc, Ubuntu 20.xx LTS, default value is enough for >200K

**Comment by MarkFried** [comment]
Similar Problem here: (latest docker file from Friday)

Er	ATDO2022-01-17 10:37:37.480  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 89803 entries.
2022-01-17 10:37:37.483  INFO --- o.a.p.s.MediaScannerService              : Persisting albums
2022-01-17 10:37:38.905  INFO --- o.a.p.s.MediaScannerService              : Persisting artists
2022-01-17 10:37:39.088  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2022-01-17 10:37:39.120  INFO --- o.a.p.s.MediaScannerService              : Album persistence complete
2022-01-17 10:37:39.347  INFO --- o.a.p.s.MediaScannerService              : Marking present files
2022-01-17 10:37:39.349  INFO --- o.a.p.s.MediaScannerService              : Persisting genres
2022-01-17 10:37:39.396  INFO --- o.a.p.s.MediaScannerService              : Updating genres
2022-01-17 10:37:39.432  INFO --- o.a.p.s.MediaScannerService              : Genre persistence successfully complete: true
2022-01-17 10:37:39.438  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.
2022-01-17 10:37:39.457  INFO --- o.a.p.s.MediaScannerService              : Artist persistence complete
Exception in thread "Catalina-utility-2" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-0.0.0.0-4040-Acceptor" java.lang.OutOfMemoryError: Java heap space
Exception in thread "http-nio-0.0.0.0-4040-Poller" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Collections$UnmodifiableCollection.iterator(Unknown Source)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.timeout(NioEndpoint.java:1026)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:828)
        at java.base/java.lang.Thread.run(Unknown Source)
2022-01-17 10:38:05.357 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.

java.util.concurrent.CompletionException: org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [update media_file set present=true, last_scanned = ? where path in (?, ?, ?, ?....

There are lots of '?' parameter place holders after this.

The machine has 16GB of RAM and a standard Java heap size of 4GB - isn't this enough?

   size_t MaxHeapSize                              = 4108320768                                {product} {ergonomic}
 uint64_t MaxRAM                                   = 137438953472                           {pd product} {default}
    uintx MaxRAMFraction                           = 4                                         {product} {default}
   double MaxRAMPercentage                         = 25.000000                                 {product} {default}
   size_t SoftMaxHeapSize                          = 4108320768                             {manageable} {ergonomic}
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
