### ISSUE TITLE
When loading a folder or album i get errors

### ISSUE THREAD

**Issue by cheskykay** [airsonic-advanced/airsonic-advanced#503]
## Problem description

When loading a floder i see in the error log some errors on meta tag not properly ended. 
also when clicking on album within that folder i get others errors. 

### Steps to reproduce

in the side bar click on the folder, then look in the error log
when folder is loaded click on one of the albums and view the errolog 

## Errors from the logs. 

[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".
[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".
[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".
[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".
[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".
[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".
[Fatal Error] :60:3: The element type "meta" must be terminated by the matching end-tag "</meta>".

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jaudiotagger.audio.mp3.MP3File (jar:file:/C:/Airsonic/airsonic.war!/WEB-INF/lib/jaudiotagger-2.2.5.jar!/) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.jaudiotagger.audio.mp3.MP3File
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210308063729 – March 8, 2021 at 1:37:29 AM EST
 * **Operating system**   * **Java version**:  :Apache Tomcat/9.0.41, java 15.0.2, Windows 10 (100.6 MB / 224.0 MB)
  * **Proxy server**:  None
 * **Client**: Chrome 

 * **Language**: English

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by cheskykay** [comment]
from airsonic.log file more detailed log

de.umass.lastfm.CallException: org.xml.sax.SAXParseException; lineNumber: 60; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>".
	at de.umass.lastfm.Caller.call(Caller.java:268) ~[lastfm-java-0.1.2.jar!/:na]
	at de.umass.lastfm.Caller.call(Caller.java:189) ~[lastfm-java-0.1.2.jar!/:na]
	at de.umass.lastfm.Artist.getInfo(Artist.java:119) ~[lastfm-java-0.1.2.jar!/:na]
	at de.umass.lastfm.Artist.getInfo(Artist.java:82) ~[lastfm-java-0.1.2.jar!/:na]
	at org.airsonic.player.service.LastFmService.getCanonicalArtistName(LastFmService.java:388) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.LastFmService.getArtistBio(LastFmService.java:222) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.ajax.ArtistWSController.getArtistInfo(ArtistWSController.java:36) ~[classes!/:11.0.0-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:171) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:120) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:565) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:520) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:454) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.3.jar!/:5.3.3]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: org.xml.sax.SAXParseException: The element type "meta" must be terminated by the matching end-tag "</meta>".
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:261) ~[na:na]
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[na:na]
	at de.umass.lastfm.Caller.createResultFromInputStream(Caller.java:324) ~[lastfm-java-0.1.2.jar!/:na]
	at de.umass.lastfm.Caller.call(Caller.java:256) ~[lastfm-java-0.1.2.jar!/:na]
	... 21 common frames omitted
