### ISSUE TITLE
Unable playing music through DLNA because exception is thrown

### ISSUE THREAD

**Issue by Dikakus** [airsonic-advanced/airsonic-advanced#517]
## Problem description

When I',m trying to play a song in a dlna client, an exception is thrown and nothing more happens. Nevertheless, I can play the same song if I use a browser (Edge for example) using the web client.

But if I use the same url that failed in the dlna client in the browser the excepction is thrown again. The url was catched from the DLNA client properties.

### Steps to reproduce

1. Access to a DLNA client.
2. Browse folders.
3. Select a song.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210309214438
 * **Operating system**: Raspbian 10 (burster)
 * **Java version**: 11.0.9.1
 * **Proxy server**: lighttp 1.4.53
 * **Client**: Philips TV, VLC, Windows 10 Player
 * **Language**: ES

[airsonic-log.txt](https://github.com/airsonic-advanced/airsonic-advanced/files/6353420/airsonic-log.txt)

**Comment by randomnicode** [comment]
Your DB seems to have some integrity violations specifically around the player that was created for the DLNA client. You can:
(1) Delete your DB and rescan and try again (delete the airsonic-data/db folder)
(2) Try fixing your DB externally by yourself by finding the offending row in the Players table and deleting it. Alternatively, post your db folder here and maybe someone can take a look and fix it
(3) Try going to the Players section in your Settings page (if you can) and clone a new player and/or delete the offending player

**Comment by Dikakus** [comment]
Thank you for your replay and your suggestions @randomnicode. As it could be a PLAYER(ID) issue, I tried to delete all my player through the web, but I can't create it anymore.

![imagen_2021-05-14_133314](https://user-images.githubusercontent.com/14204887/118264968-d5454180-b4b8-11eb-8db8-6f8bb9f125eb.png)

I tried to play a song from subsonic player in my phone and it throws the same exception. It seems that it can't create a new player. 

Any idea?

**Comment by Dikakus** [comment]
Finally, I exported all my playlists, deleted the DB, reescanned my music, e imported the playlists. Unfortunatelly, I had two news issues: first, I lost my starred songs (I will restar it again) and second I still can't play DLNA songs with my TV. The log says:

```
2021-05-25 10:05:08.933  INFO --- o.a.p.c.StreamController                 : 192.168.0.36: anonymous listening to ... (etc).
...
2021-05-25 10:05:09.015  INFO --- o.a.p.s.LoggingExceptionResolver         : 192.168.0.36: Client unexpectedly closed connection while loading http://... (etc).
```

Nevertheless, playing with vlc, it works but throws this messages:

```
2021-05-25 10:31:35.201  INFO --- o.a.p.c.StreamController                 : 192.168.0.42: anonymous listening to ... (etc)
...
2021-05-25 10:31:37.159 ERROR --- o.a.p.s.LoggingExceptionResolver         : 192.168.0.42: An exception occurred while loading http://... (etc)

org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'username' cannot be found on null
  6         at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213) ~[spring-expression-5.3.3.jar!/:5.3.3]
  7         at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-5.3.3.jar!/:5.3$
  8         at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:51) ~[spring-expression-5.3.3.jar!/:5.3.3]
  9         at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:406) ~[spring-expression-5.3.3.ja$
 10         at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92) ~[spring-expression-5.3.3.jar!/:5.3.3]

```

**Comment by randomnicode** [comment]
``` 2021-05-25 10:31:37.159 ERROR --- o.a.p.s.LoggingExceptionResolver         : 192.168.0.42: An exception occurred while loading http://... (etc)

org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'username' cannot be found on null
  6         at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213) ~[spring-expression-5.3.3.jar!/:5.3.3]
  7         at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-5.3.3.jar!/:5.3$
  8         at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:51) ~[spring-expression-5.3.3.jar!/:5.3.3]
  9         at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:406) ~[spring-expression-5.3.3.ja$
 10         at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92) ~[spring-expression-5.3.3.jar!/:5.3.3]

```

Need more detail here, there should be parent exceptions abound perhaps?

**Comment by Dikakus** [comment]
> ```
> 
> org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'username' cannot be found on null
>   6         at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:213) ~[spring-expression-5.3.3.jar!/:5.3.3]
>   7         at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-5.3.3.jar!/:5.3$
>   8         at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:51) ~[spring-expression-5.3.3.jar!/:5.3.3]
>   9         at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:406) ~[spring-expression-5.3.3.ja$
>  10         at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:92) ~[spring-expression-5.3.3.jar!/:5.3.3]
> ```
> 
> Need more detail here, there should be parent exceptions abound perhaps?

@randomnicode , I attach here the dump of the last exception when I try to access with dlna service of vlc player. Despite of the exception it plays the music. If you need the complete log let me know, please.
[airsonic-vlc-dlna.log](https://github.com/airsonic-advanced/airsonic-advanced/files/6692412/airsonic-vlc-dlna.log)

Nevertheless, the Philips TV can't play the music. It throws a 

> 2021-05-25 10:05:09.015  INFO --- o.a.p.s.LoggingExceptionResolver         : 192.168.0.36: Client unexpectedly closed connection while loading http://... (etc).

Does It seem something about login? 

The player created is identified as 'guest', and type "unknow".

Thank you.

**Comment by Dikakus** [comment]
Great news! With the new release 11.0.0-SNAPSHOT.20210702161646 the exception 

`org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'username' cannot be found on null`

is solved, but I can't play anything in my TV. The exception 

`2021-07-02 22:58:42.821  INFO --- o.a.p.s.LoggingExceptionResolver         : 192.168.0.36: Client unexpectedly closed connection while loading http://192.168.0.21:8085/airsonic/ext/stream?id=31386&player=18&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm9ueW1vdXMiLCJwYXRoIjoiL2FpcnNvbmljL2V4dC9zdHJlYW0_aWQ9MzEzODYmcGxheWVyPTE4IiwiaXNzIjoiYWlyc29uaWMiLCJleHAiOjE2MjU4NjQzMTN9.53VobA8drU5uCwYqgR1uCiFM1X-CUEX5fwy7A5gOiMA (java.io.IOException: Conexión reinicializada por la máquina remota)`

continues being thrown.
