### ISSUE TITLE
Airsonic Advanced Internet Radio

### ISSUE THREAD

**Issue by rpi-maker** [airsonic-advanced/airsonic-advanced#536]
## Problem description

I am trying to get Airsonic Advanced to play Internet TV & radio within the web browser.  However, when I click the play icon for an internet radio stream (under Internet TV & radio section), it just throws error messages in the airsonic.log file.

This feature worked great on the Stable Airsonic 10.6.2 from https://github.com/airsonic/airsonic/releases/  but would only play when setting up a link to a m3u streaming file (not a direct link to the stream, or link to the website's browser player for the stream).

While testing, I did find a link for the stream to a MP3 format which will load and play (see Option 4 below)  Options 1-3 failed to initialize.  Option 2 used to work with Stable Airsonic 10.6.2

Here is a sample of the airsonic.log file when attempting to start a stream.

1. Website's Browser Player http://v7player.wostreaming.net/854
2. 256k AAC M3U Streaming Link http://live.wostreaming.net/playlist/ppm-jazz24aac256-ibc1.m3u
3. 256k AAC Direct Streaming Link http://live.wostreaming.net/direct/ppm-jazz24aac256-ibc1
4. 128k MP3 Streaming Link https://live.wostreaming.net/direct/ppm-jazz24mp3-ibc1

_See https://www.jazz24.org/streaming-links/ for list of URLs for testing._

**Note:** I did try both http:// and https:// when testing these 4 Stream URLs, resulting in the same error messages.

``` Error Message 
org.airsonic.player.service.InternetRadioService$PlaylistFormatUnsupported: Unsupported playlist format <URL to Internet Radio Stream>
```

```
Airsonic.log
---
org.airsonic.player.service.InternetRadioService$PlaylistFormatUnsupported:  Unsupported playlist format http://v7player.wostreaming.net/854

at  org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:177)  ~[classes!/:11.0.0-SNAPSHOT]
at  org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:140)  ~[classes!/:11.0.0-SNAPSHOT]
at  org.airsonic.player.service.InternetRadioService.getInternetRadioSources(InternetRadioService.java:116)  ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.convertInternetRadio(PlayQueueService.java:559) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.getPlayQueueInfo(PlayQueueService.java:529) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.lambda$15(PlayQueueService.java:501) ~[classes!/:11.0.0-SNAPSHOT]
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
&nbsp;
2021-06-10 05:58:38.269 ERROR ---  o.a.p.s.InternetRadioService             : Failed to retrieve sources  for internet radio  http://live.wostreaming.net/playlist/ppm-jazz24aac256-ibc1.m3u.
&nbsp;
org.airsonic.player.service.InternetRadioService$PlaylistFormatUnsupported:  Unsupported playlist format  http://live.wostreaming.net/playlist/ppm-jazz24aac256-ibc1.m3u
at  org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:177)  ~[classes!/:11.0.0-SNAPSHOT]
at  org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:140)  ~[classes!/:11.0.0-SNAPSHOT]
at  org.airsonic.player.service.InternetRadioService.getInternetRadioSources(InternetRadioService.java:116)  ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.convertInternetRadio(PlayQueueService.java:559) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.getPlayQueueInfo(PlayQueueService.java:529) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.lambda$15(PlayQueueService.java:501) ~[classes!/:11.0.0-SNAPSHOT]
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
&nbsp;
2021-06-10 05:58:53.032 ERROR ---  o.a.p.s.InternetRadioService             : Failed to retrieve sources  for internet radio  http://live.wostreaming.net/direct/ppm-jazz24aac256-ibc1.
&nbsp;
org.airsonic.player.service.InternetRadioService$PlaylistFormatUnsupported:  Unsupported playlist format  http://live.wostreaming.net/direct/ppm-jazz24aac256-ibc1
at  org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:177)  ~[classes!/:11.0.0-SNAPSHOT]
at  org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:140)  ~[classes!/:11.0.0-SNAPSHOT]
at  org.airsonic.player.service.InternetRadioService.getInternetRadioSources(InternetRadioService.java:116)  ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.convertInternetRadio(PlayQueueService.java:559) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.getPlayQueueInfo(PlayQueueService.java:529) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PlayQueueService.lambda$15(PlayQueueService.java:501) ~[classes!/:11.0.0-SNAPSHOT]
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
&nbsp;
2021-06-10 05:58:57.334  INFO ---  o.a.p.s.InternetRadioService             : Retrieved playlist for  internet radio https://live.wostreaming.net/direct/ppm-jazz24mp3-ibc1,  got 1 sources.

```

### Steps to reproduce

1. Deploy Airsonic.war EDGE 11.0.0-SNAPSHOT.20210504201650
2. Login to Airsonic Advanced web interface
3. Add a few of the Internet Streaming URLS to "Settings" - "Internet TV & radio" via the Airsonic Advanced web interface
4. Click on the Play Icon on the Left under Internet TV & radio for the streams added above.

For the MP3 Streaming Link (Option 4), I also had to click the Play Button in the bottom of the Web Interface to start listening to the stream (Added Step as compared to the Stable Airsonic 10.6.2).

Not to confuse anyone, but there is also a 128k MP3 through M3U Playlist Streaming Link on the Streaming Links Page.   This 128k MP3 through M3U Playlist Streaming Link also failed to work, even though the 128k MP3 Direct Streaming Link Worked.
https://live.wostreaming.net/playlist/ppm-jazz24mp3-ibc1.m3u

## System information

Version | 11.0.0-SNAPSHOT.20210504201650 – May 4, 2021 at 3:16:50 PM CDT
-- | --
Server | Apache Tomcat/9.0.41, java 11.0.11, Linux (86.5 MB / 153.2 MB)

```
 lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
```
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.11+9-post-Raspbian-1deb10u1, mixed mode)
```

Proxy Server: None

Clients:
Chromium Version 88.0.4324.187 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit)
Firefox 89.0 (64-bit) for Windows
Google Chrome

Language: 
```
sudo cat /etc/default/locale
#  File generated by update-locale
LANG=en_US.UTF-8

```

https://github.com/airsonic/airsonic/releases/
https://github.com/airsonic-advanced/airsonic-advanced/releases

## Additional notes

If it helps, I did find some related reading materials...

Play internet radios in MediaElement #985 
https://github.com/airsonic/airsonic/pull/985

Internet Radio 10.4.0 - shoutcast playlist will not play #1169
https://github.com/airsonic/airsonic/issues/1169

[10.4.0] web radio not handling binary stream anymore #1209
https://github.com/airsonic/airsonic/issues/1209

**Comment by randomnicode** [comment]
Just putting relevant data in for future possible fixes here:

http://v7player.wostreaming.net/854 : is an html page. this will likely never play (or be supported)
http://live.wostreaming.net/direct/ppm-jazz24aac256-ibc1 : content-type is audio/aacp (currently we only play audio/mpeg only)
http://live.wostreaming.net/playlist/ppm-jazz24aac256-ibc1.m3u : content-type is audio/x-mpegurl . This plays okay for us.

**Comment by randomnicode** [comment]
With #537 and #539 this issue should be resolved now.

2, 3, 4 radios should play, 1 won't be supported. Please test on the latest edge release?

**Comment by jobenvil** [comment]
It Is content-type audio/mpeg supposed to work? I'm struggling with `http://streams1.mdtradio.com:8020/mdtweb" type="audio/mpeg"`
logs:
`2021-06-12 08:22:56.627  INFO --- o.a.p.s.InternetRadioService             : Retrieved playlist for internet radio http://streams1.mdtradio.com:8020/mdtweb, got 1 sources.`
but nothings happens.
Just wondering where if there is a content type compatible airsonic list, to search for.
`Java: 11.0.11+9-Ubuntu-0ubuntu2.20.10`
`11.0.0-SNAPSHOT.20210612032051 – June 12, 2021 at 5:20:51 AM CEST`
Using `airsonic.war (Apache Tomcat/9.0.46, java 11.0.11)` with `nginx` reverse proxy

**Comment by rpi-maker** [comment]
I tested the latest Edge Release 11.0.0-SNAPSHOT.20210612032051, and all of the .pls, .m3u, direct links are working for mpeg and aacp audio sources.


------
I also tested http://streams1.mdtradio.com:8020/mdtweb mentioned by @jobenvil, and this is also working on this latest EDGE Release.  However, there is an odd issue this one..

Using the Airsonic Advanced Web Interface, enter the following in Airsonic Advanced - Settings - Internet TV & Radio - Stream URL - then Save.
```http://streams1.mdtradio.com:8020/mdtweb" type="audio/mpeg"```
The web interface will successfully save the URL, but will display the following in the Stream URL dialog box.
```http://streams1.mdtradio.com:8020/mdtweb```

If you try to play this stream as entered as entered with the ```" type="audio/mpeg"```, it will throw an error.


**Error Message from airsonic.log**
```
2021-06-13 03:00:59.790 ERROR --- o.a.p.s.InternetRadioService             : Failed to retrieve sources for internet radio http://streams1.mdtradio.com:8020/mdtweb" type="audio/mpeg".

java.net.SocketException: Unexpected end of file from server
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[na:na]
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
        at org.airsonic.player.service.InternetRadioService.connectToURLWithRedirects(InternetRadioService.java:258) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:164) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.InternetRadioService.retrieveInternetRadioSources(InternetRadioService.java:140) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.InternetRadioService.getInternetRadioSources(InternetRadioService.java:116) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlayQueueService.convertInternetRadio(PlayQueueService.java:559) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlayQueueService.getPlayQueueInfo(PlayQueueService.java:529) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlayQueueService.lambda$15(PlayQueueService.java:501) ~[classes!/:11.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

If you click Save in the Internet TV & radio settings page a **_second time_** _(without changing anything)_, it will fix the stream to not include ``" type="audio/mpeg"`` and the media will play correctly.

Not sure where @jobenvil found this first link, looks like it is just trying to explicitly state the media type.  Visiting the URL in a web browser just shows an error page.

```
500 - Internal Server Error
---------------------------
Recursive error
```

------

Anyway, the original issue is resolved and is working correctly.


A big thanks to @randomnicode for fast resolution to this issue!

**Comment by jobenvil** [comment]
> I tested the latest Edge Release 11.0.0-SNAPSHOT.20210612032051, and all of the .pls, .m3u, direct links are working for mpeg and aacp audio sources.

> I also tested http://streams1.mdtradio.com:8020/mdtweb mentioned by @jobenvil, and this is also working on this latest EDGE Release. However, there is an odd issue this one..

I was using the same EDGE version, like you.

May I ask if you connect directly to the airsonic:port or over a reverse proxy? this is crucial to clarify. I assume you connect directly.

Anyway thanks a lot for testing my url 👍 I see I have to check what's going on, either proxy is not piping music correctly or transceivers are not properly configured...

> A big thanks to @randomnicode for fast resolution to this issue!

I second that x1000 times!

**Comment by rpi-maker** [comment]
@jobenvil 
I am currently connected directly to the airsonic:port as this is being tested as a local LAN internal web server.  Check your Stream URL if you are logging an error message, otherwise it could be with your setup...

> Anyway thanks a lot for testing my url +1 I see I have to check what's going on, either proxy is not piping music correctly or transceivers are not properly configured...

If you figure it out, and it is an issue with Airsonic Advanced, please open a new issue and reference this one for troubleshooting.

**Comment by jobenvil** [comment]
Now its clear. The issue is reproducible using reverse proxy (nginx) with https enabled:

![image](https://user-images.githubusercontent.com/11994245/121802887-1a3ad000-cc3f-11eb-8c46-fd16488bc18f.png)

Mixed content (http/https) will be converted to https. Over https is not reachable the music url.
