### ISSUE TITLE
Failed to create search index

### ISSUE THREAD

**Issue by ottopresser** [airsonic-advanced/airsonic-advanced#575]
## Problem description

When restarting airsonic in a stand alone Tomcat 8.5 instance I see this stacktrace repeat several times.

2021-07-20 13:58:38.061 ERROR --- o.a.p.s.search.IndexManager : Failed to create search index for org.airsonic.player.domain.Artist@59ac6302
--
 
java.lang.NullPointerException: null
at org.airsonic.player.service.search.IndexManager.index(IndexManager.java:126) ~[classes/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.MediaScannerService.updateArtist(MediaScannerService.java:459) ~[classes/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:320) ~[classes/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.MediaScannerService.lambda$22(MediaScannerService.java:316) ~[classes/:11.0.0-SNAPSHOT]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

Airsonic works as intended but am I missing some database search indexes?

### Steps to reproduce

This happens after restart of airsonic standalone binary.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210716201658 – July 16, 2021 at 8:16:58 PM UTC
 * **Operating system**: FreeBSD 12.2-RELEASE-p7
 * **Java version**: OpenJDK 64-Bit Server VM (build 11.0.10+9-1, mixed mode)
 * **Proxy server**: nginx-1.18.0_49,2
 * **Client**: Chrome Version 91.0.4472.124 (Official Build) (64-bit)
 * **Language**: English

**Comment by awsms** [comment]
I've the same issue here. 

check out https://github.com/airsonic-advanced/airsonic-advanced/issues/384 and see if you have `Caused by: java.sql.SQLException: Data too long for column` somewhere in your logfile.

unfortunately I don't, so i have no idea where that's coming from :/

**Comment by ultsi** [comment]
I had this issue until I discovered my airsonic container didn't have `x (execute)` rights to some album folders. Running `chmod 755` on those folders made the issue go away and indexing could resume. So @randomnicode adding a line that checks folder can be searched inside for children mediafiles could get rid of this error or make the root cause easier to find.

**Comment by blablup** [comment]
I had the same issue. I also saw that I had music files with invalid chars in some folders. I fixed all the file names with the [detox](https://github.com/dharple/detox) tool. With a restart the library scan was fine.
