### ISSUE TITLE
Airsonic doesn't bind to ipv6 addresses

### ISSUE THREAD

**Issue by echoxxzz** [airsonic-advanced/airsonic-advanced#584]
Airsonic only binds to ipv4. I've tried setting the -Dserver.address parameter for the JVM to ipv6 addresses but it only seems to accept ipv4 addresses.

*Describe your problem here. Describe what you want to happen, and what happens
if you try to do it. If you have a stack trace or any logs, please format them using
github's triple-backquote notation, or if they are large you may also consider
attaching them as a file or gist.*

1. Start Airsonic
2. sockstat -l only shows Airsonic binding to TCP4 addresses

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20210716201658
 * **Operating system**: FreeBSD 13.0p3
 * **Java version**: 11.0.11+9.1
 * **Proxy server**: None
 * **Client**: Edge  92.0.902.62
 * **Language**: English

## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by uqs** [comment]
Same problem here, my jails are IPv6 only, while subsonic runs fine, airsonic-advanced barfs during startup and there's no obvious property to set to have it bind to IPv6 instead.

```
Caused by: java.net.SocketException: Protocol not supported
        at java.base/sun.nio.ch.Net.socket0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.serverSocket(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.ServerSocketChannelImpl.<init>(Unknown Source) ~[na:na]
        at java.base/sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(Unknown Source) ~[na:na]
        at java.base/java.nio.channels.ServerSocketChannel.open(Unknown Source) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:271) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:229) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1313) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.60.jar!/:na]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072) ~[tomcat-embed-core-9.0.60.jar!/:na]
        ... 27 common frames omitted

```

**Comment by fault1er1** [comment]
> Same problem here, my jails are IPv6 only, while subsonic runs fine, airsonic-advanced barfs during startup and there's no obvious property to set to have it bind to IPv6 instead.
> 
> ```
> Caused by: java.net.SocketException: Protocol not supported
>         at java.base/sun.nio.ch.Net.socket0(Native Method) ~[na:na]
>         at java.base/sun.nio.ch.Net.serverSocket(Unknown Source) ~[na:na]
>         at java.base/sun.nio.ch.ServerSocketChannelImpl.<init>(Unknown Source) ~[na:na]
>         at java.base/sun.nio.ch.SelectorProviderImpl.openServerSocketChannel(Unknown Source) ~[na:na]
>         at java.base/java.nio.channels.ServerSocketChannel.open(Unknown Source) ~[na:na]
>         at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:271) ~[tomcat-embed-core-9.0.60.jar!/:na]
>         at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:229) ~[tomcat-embed-core-9.0.60.jar!/:na]
>         at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227) ~[tomcat-embed-core-9.0.60.jar!/:na]
>         at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1313) ~[tomcat-embed-core-9.0.60.jar!/:na]
>         at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.60.jar!/:na]
>         at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072) ~[tomcat-embed-core-9.0.60.jar!/:na]
>         ... 27 common frames omitted
> ```

Better file this bug to kagegomiji/airsonic-advanced, since this project is abandoned for years.
