### ISSUE TITLE
Error 500 in home.view on fresh migration from subsonic

### ISSUE THREAD

**Issue by khers** [airsonic-advanced/airsonic-advanced#599]
## Problem description

When clicking Home, Playing, or Starred I get a 500 error in the main panel with the message "Access denied to file <Song Name>" where the Song Name changes each time I click.  I have check permissions on my music collection, the user running airsonic has read/write on all of it.

I just migrated from subsonic 6.1.6 and this error has been present from the first use after migration.

The exception shown is: 
```
                        java.lang.SecurityException: Access denied to file Stealth
	at org.airsonic.player.service.MediaFileService.getMediaFile(MediaFileService.java:143)
	at org.airsonic.player.service.search.SearchServiceUtilities.addIgnoreNull(SearchServiceUtilities.java:142)
	at org.airsonic.player.service.search.SearchServiceImpl.lambda$2(SearchServiceImpl.java:156)
	at org.airsonic.player.service.search.SearchServiceImpl.createRandomDocsList(SearchServiceImpl.java:113)
	at org.airsonic.player.service.search.SearchServiceImpl.getRandomAlbums(SearchServiceImpl.java:155)
	at org.airsonic.player.controller.HomeController.getRandom(HomeController.java:195)
	at org.airsonic.player.controller.HomeController.handleRequestInternal(HomeController.java:101)
	at sun.reflect.GeneratedMethodAccessor587.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:503)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:49)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:56)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
...
```

### Steps to reproduce

Migrate

## System information

 * **Airsonic version**: 10.6.0.20200424173747 – April 24, 2020 5:37:47 PM UTC
 * **Operating system**: Ubuntu 20.04
 * **Java version**: OpenJDK 1.8.0_292
 * **Proxy server**: Apache 2.4.41
 * **Client**: Firefox 91.0
 * **Language**: en_US
 *

**Comment by randomnicode** [comment]
(1) you should be using the latest edge versions (might have to update java)
(2) check if the folder is in a parent that has been assigned as a media folder. Is `Bad\ Religion` in a Media Folder? If not add the parent (whatever `./` is) as a Media Folder in settings

**Comment by khers** [comment]
It seems to have resolved itself (the folder containing all my music was listed as a Media Folder so that wasn't the issue.

I am trying to upgrade to an edge version and that is now broken, will open a new issue
