### ISSUE TITLE
airsonic is slow is standalone war mode

### ISSUE THREAD

**Issue by retropc** [airsonic-advanced/airsonic-advanced#602]
in standalone (i.e. java -jar airsonic.war) mode:  whenever airsonic is loading a class from the war file it is very very slow (e.g. when doing something you haven't done since you started the server)

if I kill -3 it is always stuck at 100% cpu on:

```
"http-nio-8080-exec-43" #81 daemon prio=5 os_prio=0 cpu=9258.68ms elapsed=36.52s tid=0x4d399000 nid=0x161e runnable  [0x4861b000]
   java.lang.Thread.State: RUNNABLE
        at java.io.RandomAccessFile.readBytes(java.base@11.0.12/Native Method)
        at java.io.RandomAccessFile.read(java.base@11.0.12/RandomAccessFile.java:406)
        at java.util.zip.ZipFile$Source.readAt(java.base@11.0.12/ZipFile.java:1352)
        - locked <0x55e32350> (a java.io.RandomAccessFile)
        at java.util.zip.ZipFile$ZipFileInputStream.read(java.base@11.0.12/ZipFile.java:1029)
        - locked <0x5fe6dd78> (a java.util.jar.JarFile)
        at java.io.FilterInputStream.read(java.base@11.0.12/FilterInputStream.java:133)
        at java.io.PushbackInputStream.read(java.base@11.0.12/PushbackInputStream.java:183)
        at java.util.zip.InflaterInputStream.fill(java.base@11.0.12/InflaterInputStream.java:243)
        at java.util.zip.InflaterInputStream.read(java.base@11.0.12/InflaterInputStream.java:159)
        at java.util.zip.ZipInputStream.read(java.base@11.0.12/ZipInputStream.java:197)
        at java.util.jar.JarInputStream.read(java.base@11.0.12/JarInputStream.java:207)
        at java.util.zip.ZipInputStream.closeEntry(java.base@11.0.12/ZipInputStream.java:143)
        at java.util.zip.ZipInputStream.getNextEntry(java.base@11.0.12/ZipInputStream.java:121)
        at java.util.jar.JarInputStream.getNextEntry(java.base@11.0.12/JarInputStream.java:142)
        at java.util.jar.JarInputStream.getNextJarEntry(java.base@11.0.12/JarInputStream.java:179)
        at org.apache.catalina.webresources.JarWarResourceSet.getArchiveEntries(JarWarResourceSet.java:117)
        - locked <0x5a280c18> (a java.lang.Object)
        at org.apache.catalina.webresources.AbstractArchiveResourceSet.getResource(AbstractArchiveResourceSet.java:260)
        at org.apache.catalina.webresources.StandardRoot.getResourceInternal(StandardRoot.java:281)
        at org.apache.catalina.webresources.Cache.getResource(Cache.java:62)
        at org.apache.catalina.webresources.StandardRoot.getResource(StandardRoot.java:216)
        at org.apache.catalina.webresources.StandardRoot.getClassLoaderResource(StandardRoot.java:225)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2359)
        at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:870)
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.findClassIgnoringNotFound(TomcatEmbeddedWebappClassLoader.java:123)
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.doLoadClass(TomcatEmbeddedWebappClassLoader.java:88)
        at org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader.loadClass(TomcatEmbeddedWebappClassLoader.java:70)
```

this seems to be a bug in the Tomcat JarWarResourceSet in spring boot: https://github.com/spring-projects/spring-boot/issues/16471

running it as an unpacked war as a jar is about 1000x faster!

**Comment by aeleeds** [comment]
Oh how interesting. For those who barely have the knowhow to get airsonic working, like myself, could you tell me how I would unpack the war into a jar and modify systemctl setup (if needed) so it works correctly? I would love to get a speed boost. Initial login and opening any of the top level webpages (playing, settings, status) are painfully slow.

**Comment by retropc** [comment]
hi

that should be "running it as an unpacked war OR as a jar is about 1000x faster!"

you can either:
1. run it as a standard war inside tomcat or another servlet container
2. or hack it to compile as a jar

for solution 2: https://github.com/retropc/airsonic-advanced/tree/run-from-jar (diff: https://github.com/retropc/airsonic-advanced/commit/d46a6444b1ca56bd37ca33574347029d8cd0a557)

it's nasty but it works

just check out the code and run:

```mvn package -DskipTests```

that will produce you airsonic-main/target/airsonic.jar, copy this to where you have airsonic.war currently and change any references in your systemd config from the .war to .jar

it should then start up and act in general several thousand times faster!

(I have no doubt there's a proper spring-boot way of doing this, however my patience for messing around with spring these days is quite limited!)

**Comment by retropc** [comment]
other possible ways to fix it:
- monkeypatch the tomcat jarwar loader to figure out that it's in an uncompressed jar
- switch from tomcat embedded to jetty

**Comment by MichaIng** [comment]
I can confirm that the current v10.6.0 and latest v11 snapshots *.war builds are extremely slow on Debian, v10.6.0 tested on Stretch with Java 8, both versions on Buster with Java 11, and v11 snapshot on Bullseye with Java 17 + Java 11. Java always installed via `openjdk-8/11/17-jre-headless` package. The first load of every single page or button raises CPU frequency for several seconds to 100% before the action/page load happens. Subsequent requests are faster.

The *.jar build of @retropc works fast right from the start. I'm not sure about the implications or downsides on other platforms, but probably it makes sense to provide both variants with releases so users can pick the one which works better in their case.

**Comment by MichaIng** [comment]
I'm wondering why this has not been recognised or solved years ago. The same issue appears with the original Airsonic as well. Is everyone deploying it via Tomcat or as Docker container, where suspectedly this isn't an issue? With Airsonic as only Java application this however implies unnecessary overhead compared to a direct `java -jar`.

**Comment by aeleeds** [comment]
I have this issue too, and it takes like 10 minutes to load a page for the first time on my raspberry pi 2b. It's brutal. Retropc's build is now over 200 commits behind. What's my best option at this point, if I don't have the knowhow to replicate it myself? Switching to a Tomcat deployment?

**Comment by clach04** [comment]
Me too post 😛 

Today I tried with recent AA - https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20220625052932 painful slow (to the point where it seems to have crashed a few times, massive java stack trace output).

Then tried https://github.com/retropc/airsonic-advanced/releases/tag/11.0.0-retropc-1-SNAPSHOT - this failed for me on login, as the upstream AA database appears to be different. Once I wiped out /var/airsonic/ and started again the jar version is extremely snappy in comparison.

**Comment by galgofa** [comment]
> Then tried https://github.com/retropc/airsonic-advanced/releases/tag/11.0.0-retropc-1-SNAPSHOT - this failed for me on login, as the upstream AA database appears to be different. Once I wiped out /var/airsonic/ and started again the jar version is extremely snappy in comparison.

Can you help me please to get log in ? My system is dietpi, i have managed to replace war with jar, airsonic start and run but can't get to login.

**Comment by MichaIng** [comment]
Try the following as root user or via `sudo` (which will remove all Airsonic config and data):
```sh
systemctl stop airsonic
rm -R /mnt/dietpi_userdata/airsonic
mkdir -p /mnt/dietpi_userdata/airsonic/transcode
curl -L 'https://github.com/retropc/airsonic-advanced/releases/download/11.0.0-retropc-1-SNAPSHOT/airsonic.jar' -o /mnt/dietpi_userdata/airsonic/airsonic.jar
ln -s "$(command -v ffmpeg)" /mnt/dietpi_userdata/airsonic/transcode
chown airsonic:root /mnt/dietpi_userdata/airsonic
sed -i 's/airsonic.war/airsonic.jar/' /etc/systemd/system/airsonic.service
systemctl daemon-reload
systemctl start airsonic
```

**Comment by galgofa** [comment]
> On DietPi, try the following as root user or via `sudo` (which will remove all Airsonic config and data):

Thank you very much. I did it as you advice. Seems all ok after that i have clean install, but small issue in the setting where you choose  players it return error:

`Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Wed Nov 02 11:05:23 EET 2022
There was an unexpected error (type=Internal Server Error, status=500).
java.lang.NoClassDefFoundError: Could not initialize class com.github.biconou.AudioPlayer.AudioSystemUtils
	at org.airsonic.player.controller.PlayerSettingsController.formBackingObject(PlayerSettingsController.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`

**Comment by MichaIng** [comment]
Not sure if it is related, but in older Airsonic-Advanced versions there was an issue with the default audio player, added on fresh installs. It had to be removed and recreated to be functional.

**Comment by galgofa** [comment]
> It had to be removed and recreated to be functional.

Sorry to ask but how to do that ? I have tried to reinstall dietpi version of airsonic and delete all players were there. Install again jar, still same issue.

**Comment by MichaIng** [comment]
@galgofa 
Did you find it? (Saw removed comment) The player section in settings/setup of Airsonic's web interface I meant.
