### ISSUE TITLE
clean install running under tomcat 9 starts once, but fails second time

### ISSUE THREAD

**Issue by retropc** [airsonic-advanced/airsonic-advanced#604]
first run is fine

once the server is shut down and restarted the server tries to load the hsqldb driver and fails (because it's presumably not in the war):

it then determines that this means the database should be upgraded, which also attempts to load the driver, and also fails

at this point the startup terminates

```
tomcat9[13458]: 2021-08-23 00:00:45.035  WARN --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database driver version cannot be determined. Will make a copy of the DB prior to connecting. This may upgrade the database from version 2.5.0
tomcat9[13458]: java.sql.SQLException: No suitable driver
tomcat9[13458]:         at java.sql/java.sql.DriverManager.getDriver(DriverManager.java:298) ~[java.sql:na]
tomcat9[13458]:         at org.airsonic.player.util.LegacyHsqlMigrationUtil.isHsqlDbBackupNeeded(LegacyHsqlMigrationUtil.java:72) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:148) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:17) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:1) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.boot.context.event.EventPublishingRunListener.contextPrepared(EventPublishingRunListener.java:89) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.lambda$contextPrepared$3(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:404) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174) ~[spring-web-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
tomcat9[13458]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
tomcat9[13458]:         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat9-util-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[na:na]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1575) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
tomcat9[13458]:         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat9-util-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.Catalina.start(Catalina.java:633) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
tomcat9[13458]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
tomcat9[13458]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
tomcat9[13458]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
tomcat9[13458]:         at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343) ~[bootstrap.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) ~[bootstrap.jar:9.0.31]
tomcat9[13458]: 2021-08-23 00:00:45.090  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /var/airsonic/db.backup.20210823000045
tomcat9[13458]: 2021-08-23 00:00:45.309 ERROR --- o.s.boot.SpringApplication               : Application run failed
tomcat9[13458]: java.lang.RuntimeException: Failed to upgrade HSQLDB database
tomcat9[13458]:         at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:160) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:17) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:1) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.springframework.boot.context.event.EventPublishingRunListener.contextPrepared(EventPublishingRunListener.java:89) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.lambda$contextPrepared$3(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:404) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:175) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:155) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:97) ~[spring-boot-2.5.2.jar:2.5.2]
tomcat9[13458]:         at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174) ~[spring-web-5.3.8.jar:5.3.8]
tomcat9[13458]:         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
tomcat9[13458]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
tomcat9[13458]:         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat9-util-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118) ~[na:na]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:772) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1575) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
tomcat9[13458]:         at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat9-util-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
tomcat9[13458]:         at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.Catalina.start(Catalina.java:633) ~[tomcat9-catalina-9.0.31.jar:9.0.31]
tomcat9[13458]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
tomcat9[13458]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
tomcat9[13458]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
tomcat9[13458]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
tomcat9[13458]:         at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343) ~[bootstrap.jar:9.0.31]
tomcat9[13458]:         at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478) ~[bootstrap.jar:9.0.31]
tomcat9[13458]: Caused by: java.sql.SQLException: No suitable driver found for jdbc:hsqldb:file:/var/airsonic/db/airsonic;hsqldb.tx=mvcc;sql.enforce_size=false;sql.char_literal=false;sql.nulls_first=false;hsqldb.defrag_limit=50;shutdown=true
tomcat9[13458]:         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702) ~[java.sql:na]
tomcat9[13458]:         at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:189) ~[java.sql:na]
tomcat9[13458]:         at org.airsonic.player.util.LegacyHsqlMigrationUtil.getHsqlDbConnection(LegacyHsqlMigrationUtil.java:45) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.util.LegacyHsqlMigrationUtil.performHsqlDbUpgrade(LegacyHsqlMigrationUtil.java:123) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:157) ~[classes/:11.0.0-SNAPSHOT]
tomcat9[13458]:         ... 58 common frames omitted
```

it seems silly to try upgrading if the db driver couldn't be loaded

**Comment by randomnicode** [comment]
> because it's presumably not in the war

It's there. It's in `lib/`

> once the server is shut down and restarted the server tries to load the hsqldb driver and fails
> it then determines that this means the database should be upgraded, which also attempts to load the driver, and also fails
> it seems silly to try upgrading if the db driver couldn't be loaded

There is actually a bit more nuance here. There are two intermingled issues here:
 - To *backup* the old db
 - To *upgrade* the old db

The new driver automatically upgrades the db just by connecting to it, so we DON'T want it to connect first.

So here's what actually happens:
- The check is run every startup
- The db properties file is read OUTSIDE of the driver.
- It is compared to the driver version and then determined whether or not a backup needs to be made. The decision matrix and accompanying reasoning is here: https://github.com/airsonic/airsonic/pull/1345#discussion_r341830519

Now if a driver isn't found, the application will fail regardless of what happens: there is nothing to connect to the db with. There is nothing to do regarding an upgrade either: there is no driver. The only decision point in that scenario is whether to create a db backup or not, which was decided in prudence that we should do.

The accompanying PR, all it's doing is not making a backup. Upgrades are not something it affects or can affect.

**Comment by retropc** [comment]
I agree the underlying issue is that the legacy driver isn't being loaded correctly

that combined with the bad logic in LegacyHsqlMigrationUtil is causing the problem

### the problem

the first time the application starts up without issue (because there's no database)

the second time:
1. the application tried loading the "legacy" DB driver, which fails
2. it makes a copy of the database (works)
3. it then tries loading the legacy driver again, which fails again, this then terminates the application

### reproducing

you can reproduces the issue on a fresh debian11 install on amd64:

- apt install tomcat9
- mkdir /var/airsonic && chown tomcat:tomcat /var/airsonic
- systemctl stop tomcat9
- systemctl edit tomcat9
```
[Service]
ReadWritePaths=/var/airsonic/
```
- copy airsonic.war into /var/lib/tomcat9/webapps (I'm using https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20210824022700)
- systemctl start tomcat9
- wait for it to start up
- systemctl restart tomcat9
- (application falls over with the exceptions above)

### theory

I suspect it's because LegacyHsqlMigrationUtil's manual instantiation of the database driver is subtly different to how spring is doing it (possibly even a boot classpath issue given it's tomcat)

**Comment by retropc** [comment]
the patch shortcircuits the dodgy logic in LegacyHsqlMigrationUtil if it can't load the driver

(spring then correctly loads the driver and everything works as expected)

**Comment by retropc** [comment]
yeah, it's a classloader issue

loading the db driver manually is "naughty" and doesn't work as expected with tomcat's million classpaths

this guy tried fixing it: https://github.com/airsonic/airsonic/pull/1750/files

**Comment by retropc** [comment]
okay, this works, see https://github.com/airsonic-advanced/airsonic-advanced/pull/605

**Comment by retropc** [comment]
fixed
