### ISSUE TITLE
Advanced Airsonic install on synology NAS

### ISSUE THREAD

**Issue by GenesisAdam** [airsonic-advanced/airsonic-advanced#632]
## Problem description

*I installed on synology nas x64 but the container gets stuck on starting.*
Log:

2021-09-23T21:03:34.542202450Z Docker USER id: 1024
2021-09-23T21:03:34.542963906Z Docker PUID env: 0
2021-09-23T21:03:34.545985655Z Docker USER group: 101
2021-09-23T21:03:34.546151969Z Docker PGID env: 0
2021-09-23T21:03:34.675836877Z Process will run as:
2021-09-23T21:03:34.680700266Z User: 1024
2021-09-23T21:03:34.682812115Z Group: 101
2021-09-23T21:03:36.509043478Z openjdk 14.0.2 2020-07-14
2021-09-23T21:03:36.824185714Z OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
2021-09-23T21:03:36.824281305Z OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
2021-09-23T21:03:36.824334579Z JAVA_OPTS=-Dserver.forward-headers-strategy=native
2021-09-23T21:03:50.215773692Z ffmpeg version 4.4-1ubuntu0~20.04.sav0.1 Copyright (c) 2000-2021 the FFmpeg developers
2021-09-23T21:03:50.216460547Z built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
2021-09-23T21:03:50.216544629Z configuration: --prefix=/usr --extra-version='1ubuntu0~20.04.sav0.1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libdav1d --enable-libzimg --enable-crystalhd --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
2021-09-23T21:03:50.216713806Z libavutil      56. 70.100 / 56. 70.100
2021-09-23T21:03:50.216780793Z libavcodec     58.134.100 / 58.134.100
2021-09-23T21:03:50.216829052Z libavformat    58. 76.100 / 58. 76.100
2021-09-23T21:03:50.216870087Z libavdevice    58. 13.100 / 58. 13.100
2021-09-23T21:03:50.216910964Z libavfilter     7.110.100 /  7.110.100
2021-09-23T21:03:50.216951698Z libavresample   4.  0.  0 /  4.  0.  0
2021-09-23T21:03:50.216995479Z libswscale      5.  9.100 /  5.  9.100
2021-09-23T21:03:50.217036364Z libswresample   3.  9.100 /  3.  9.100
2021-09-23T21:03:50.217076262Z libpostproc    55.  9.100 / 55.  9.100
2021-09-23T21:03:50.238258409Z curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
2021-09-23T21:03:50.238484681Z Release-Date: 2020-01-08
2021-09-23T21:03:50.238532337Z Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
2021-09-23T21:03:50.238595480Z Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
2021-09-23T21:03:50.240999324Z PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2021-09-23T21:03:50.241177218Z CONTEXT_PATH=/
2021-09-23T21:04:13.683973189Z            _                       _          
2021-09-23T21:04:13.684563366Z      /\   (_)                     (_)         
2021-09-23T21:04:13.684638958Z     /  \   _ _ __  ___  ___  _ __  _  ___     
2021-09-23T21:04:13.684687623Z    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|    
2021-09-23T21:04:13.684727886Z   / ____ \| | |   \__ \ (_) | | | | | (__     
2021-09-23T21:04:13.684789856Z  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|    
2021-09-23T21:04:13.684836484Z                                                
2021-09-23T21:04:13.684874340Z                         
2021-09-23T21:04:13.684911421Z 
2021-09-23T21:04:13.684947873Z 
2021-09-23T21:04:13.684983301Z 
2021-09-23T21:04:16.198903185Z 2021-09-23 22:04:16.192  WARN --- o.a.p.u.LegacyHsqlMigrationUtil          : Failed to determine HSQLDB database version
2021-09-23T21:04:16.199488903Z 
2021-09-23T21:04:16.199553750Z java.io.FileNotFoundException: /var/airsonic/db/airsonic.properties
2021-09-23T21:04:16.199601915Z 	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:189) ~[spring-core-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.199674504Z 	at org.springframework.core.io.support.PropertiesLoaderUtils.fillProperties(PropertiesLoaderUtils.java:144) ~[spring-core-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.199726204Z 	at org.springframework.core.io.support.PropertiesLoaderUtils.loadProperties(PropertiesLoaderUtils.java:133) ~[spring-core-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.199799100Z 	at org.airsonic.player.util.LegacyHsqlMigrationUtil.getHsqlDbVersion(LegacyHsqlMigrationUtil.java:31) ~[classes/:na]
2021-09-23T21:04:16.199863252Z 	at org.airsonic.player.util.LegacyHsqlMigrationUtil.isHsqlDbBackupNeeded(LegacyHsqlMigrationUtil.java:64) ~[classes/:na]
2021-09-23T21:04:16.199912693Z 	at org.airsonic.player.util.LegacyHsqlMigrationUtil.upgradeFileHsqlDbIfNeeded(LegacyHsqlMigrationUtil.java:159) ~[classes/:na]
2021-09-23T21:04:16.199960180Z 	at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:17) ~[classes/:na]
2021-09-23T21:04:16.200008209Z 	at org.airsonic.player.spring.StartupEventListener.onApplicationEvent(StartupEventListener.java:1) ~[classes/:na]
2021-09-23T21:04:16.200057469Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.200109987Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.200166378Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.200216501Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.8.jar:5.3.8]
2021-09-23T21:04:16.200264779Z 	at org.springframework.boot.context.event.EventPublishingRunListener.contextPrepared(EventPublishingRunListener.java:89) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200319317Z 	at org.springframework.boot.SpringApplicationRunListeners.lambda$contextPrepared$3(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200413644Z 	at java.base/java.util.ArrayList.forEach(Unknown Source) ~[na:na]
2021-09-23T21:04:16.200461233Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200574937Z 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200624871Z 	at org.springframework.boot.SpringApplicationRunListeners.contextPrepared(SpringApplicationRunListeners.java:67) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200675180Z 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:404) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200724117Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200781011Z 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144) ~[spring-boot-2.5.2.jar:2.5.2]
2021-09-23T21:04:16.200829478Z 	at org.airsonic.player.Application.main(Application.java:70) ~[classes/:na]
2021-09-23T21:04:16.200875675Z 
2021-09-23T21:04:16.216325479Z 2021-09-23 22:04:16.215  INFO --- org.airsonic.player.Application          : Starting Application using Java 14.0.2 on 717f5cc4945c with PID 11 (/app/WEB-INF/classes started by ? in /var)
2021-09-23T21:04:16.222998996Z 2021-09-23 22:04:16.222  INFO --- org.airsonic.player.Application          : No active profile set, falling back to default profiles: default
2021-09-23T21:04:44.907134276Z Docker USER id: 1024
2021-09-23T21:04:44.907926537Z Docker PUID env: 0
2021-09-23T21:04:44.910174218Z Docker USER group: 101
2021-09-23T21:04:44.910346793Z Docker PGID env: 0
2021-09-23T21:04:44.914648040Z Process will run as:
2021-09-23T21:04:44.917062408Z User: 1024
2021-09-23T21:04:44.919880479Z Group: 101
2021-09-23T21:04:45.119682528Z openjdk 14.0.2 2020-07-14
2021-09-23T21:04:45.120136055Z OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
2021-09-23T21:04:45.120487137Z OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
2021-09-23T21:04:45.164164877Z JAVA_OPTS=-Dserver.forward-headers-strategy=native
2021-09-23T21:04:52.716301301Z ffmpeg version 4.4-1ubuntu0~20.04.sav0.1 Copyright (c) 2000-2021 the FFmpeg developers
2021-09-23T21:04:52.751619064Z built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)

### Steps to reproduce
I use this compose file below:
`# AirSonic - Music Server
version: "3.7"

services:
  advsonic:
    container_name: advsonic
    image: airsonicadvanced/airsonic-advanced:latest
    #depends_on:
     # - mariadb
    restart: unless-stopped
    networks:
      t2_proxy:
    security_opt:
      - no-new-privileges:true
    ports:
      - "4040:4040"
      #- "4041:4041" #UPnp
    user: 1024:101
    volumes:
      - /volume1/Media/MediaHome/Music:/var/music
      - /volume1/Media/MediaHome/Audiobooks:/var/books
      - /volume1/docker/airsonic/podcasts:/var/podcasts
      - /volume1/docker/airsonic/playlists:/var/playlists
      - /volume1/docker/airsonic/config:/var/airsonic
    environment:
      #- spring_datasource_url='jdbc:mysql://mariadb:3306/airsonic'
      #- spring.datasource.driver-class-name='org.mariadb.jdbc.Driver'
      #- spring_datasource_username='advair'
      #- spring_datasource_password='advair'
      #- spring_liquibase_parameters_userTableQuote='"'
      - CONTEXT_PATH=/
      - TZ=Europe/London
      #- JAVA_OPTS=-Dserver.use-forward-headers=true
      - JAVA_OPTS=-Dserver.forward-headers-strategy=native #optional - if you use a reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=t2_proxy"

      # Routers
      - "traefik.http.routers.airsonic.entrypoints=http"
      - "traefik.http.routers.airsonic.rule=Host(`advsonic.ebony4life.com`)"
      - "traefik.http.routers.airsonic.middlewares=airsonic-https-redirect"
      - "traefik.http.routers.airsonic-secure.entrypoints=https"
      - "traefik.http.routers.airsonic-secure.rule=Host(`advsonic.ebony4life.com`)"
      - "traefik.http.routers.airsonic-secure.tls=true"
      - "traefik.http.routers.airsonic-secure.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.airsonic-secure.service=airsonic"

      # Service definition
      - "traefik.http.services.airsonic.loadbalancer.server.port=4040"

      # Middleware definitions
      - "traefik.http.middlewares.airsonic-https-redirect.redirectscheme.scheme=https"

      - "traefik.passHostHeader=true"
networks:
  t2_proxy:
    external: true
    name: t2_proxy`

## System information
Synology NAS DS218+
Processor: x64
Installed java: OpenJDK versions 8 and 11

## Additional notes

*Airsonic was running fine on the NAS for many years and I just decided to remove it and install advanced airsonic fresh*
Any help will be greatly appreciated.

**Comment by randomnicode** [comment]
The first error is normal. It's posting that it's unable to find a DB (because you have a new install).
However, it seems that your container is restarting before airsonic has started.

```
2021-09-23T21:04:16.222998996Z 2021-09-23 22:04:16.222 INFO --- org.airsonic.player.Application : No active profile set, falling back to default profiles: default

<container likely restarts while airsonic was initializing>

2021-09-23T21:04:44.907134276Z Docker USER id: 1024
```

Perhaps give the container some more time if there are healthchecks that are restarting the container?

**Comment by GenesisAdam** [comment]
@randomnicode Thanks for your response. I will re-install again.
Will report any progress or otherwise.

**Comment by GenesisAdam** [comment]
@randomnicode Re-installed but still not working with following error messages in the log file:

2021-09-27 17:56:28.116  WARN --- ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'themeSource': Unsatisfied dependency expressed through method 'setSettingsService' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'settingsService': Unsatisfied dependency expressed through field 'internetRadioDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internetRadioDao': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=db)(port=3306)(type=master) : Socket fail to connect to host:db, port:3306. db
2021-09-27 17:56:28.350 ERROR --- o.s.boot.SpringApplication               : Application run failed

Using this code snippet for database connection:
environment:
      - spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
      - spring.datasource.url=jdbc:mariadb://db:3306/advsonic
      - spring_datasource_username='advair'
      - spring_datasource_password='advair'
      - spring_liquibase_parameters_userTableQuote='"'
      
I am re-using a mariadb database docker which is already installed.
Thanks.

**Comment by randomnicode** [comment]
Hi,

Your airsonic container cannot see your mariadb container. They're not on the same network. Each container is isolated.

Please see a sample docker-compose to see how to have multiple services/containers talk to each other.

**Comment by GenesisAdam** [comment]
@randomnicode Both were on the same network, that was why I was surprised that the airsonic was not connecting to the database. I decided to remove the connection to mariadb and the airsonic was successfully started. I will move it to mariadb later after investigating what happened. Many thanks for your help. I can now close this.
