### ISSUE TITLE
Working FLAC Files cause player to hang

### ISSUE THREAD

**Issue by folic86** [airsonic-advanced/airsonic-advanced#658]
## Problem description

I have ripped some albums using the FLAC format. When playing through VLC locally, they work fine, but for some reason certain albums won't play through the web player and just hang at 00:00.  I don't transcode, and all the others play fine as I say.
![asnc](https://user-images.githubusercontent.com/72623015/139836543-9a376fc6-7025-4f31-9985-79d2bbb1f831.PNG)

I am running on Unraid and streaming through chrome on w10 across a LAN.

Logs below.

```<html>
<body>
<!--StartFragment-->

at org.airsonic.player.service.PlaylistService.lambda$15(PlaylistService.java:329) ~[classes!/:10.6.0]
--
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_281]
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_281]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_281]
at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[na:1.8.0_281]
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:1.8.0_281]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_281]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_281]
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_281]
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_281]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_281]
at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_281]
at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:327) ~[classes!/:10.6.0]
at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:308) ~[classes!/:10.6.0]
at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:195) ~[classes!/:10.6.0]
at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) ~[na:1.8.0_281]
at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) ~[na:1.8.0_281]
at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) ~[na:1.8.0_281]
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_281]
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[na:1.8.0_281]
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[na:1.8.0_281]
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[na:1.8.0_281]
 
2021-11-02 03:00:02.069 INFO --- o.a.p.service.PlaylistService : Completed playlist import.
2021-11-02 09:24:18.278 INFO --- o.a.p.service.PodcastService : Starting scheduled Podcast refresh.
2021-11-02 09:24:18.307 INFO --- o.a.p.service.PodcastService : Completed scheduled Podcast refresh.
2021-11-02 10:38:51.559 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: ianb \| EventType: CREATED \| Old value: null \| New value: ianb [admin] [settings] [download] [upload] [coverart] [comment] [podcast] [stream] [jukebox] [share]
2021-11-02 10:38:51.776 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves/Disobey/(01) Officer Down - Bad Wolves.flac \| EventType: CREATED \| Old value: null \| New value: Officer Down
2021-11-02 10:38:51.779 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves/Disobey \| EventType: CREATED \| Old value: null \| New value: Disobey
2021-11-02 10:38:51.790 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media \| EventType: CREATED \| Old value: null \| New value: media
2021-11-02 10:38:52.198 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves \| EventType: CREATED \| Old value: null \| New value: Bad Wolves
2021-11-02 10:38:56.194 INFO --- o.a.p.c.StreamController : 192.168.1.1: ianb listening to Dirty Deeds Done Dirt Cheap (1976)/01 - Dirty Deeds Done Dirt Cheap.flac
2021-11-02 10:38:56.197 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/AC DC/Dirty Deeds Done Dirt Cheap (1976) \| EventType: CREATED \| Old value: null \| New value: Dirty Deeds Done Dirt Cheap (1976)
2021-11-02 10:38:56.198 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/AC DC/Dirty Deeds Done Dirt Cheap (1976) \| EventType: REMOVED \| Old value: Dirty Deeds Done Dirt Cheap (1976) \| New value: null
2021-11-02 10:38:56.209 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/AC DC/Dirty Deeds Done Dirt Cheap (1976) \| EventType: CREATED \| Old value: null \| New value: Dirty Deeds Done Dirt Cheap (1976)
2021-11-02 10:38:56.400 WARN --- o.a.p.s.s.LastFMScrobbler : Failed to scrobble song 'Dirty Deeds Done Dirt Cheap' at Last.fm. Wrong username or password.
2021-11-02 10:38:59.223 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: ianb \| EventType: REMOVED \| Old value: ianb [admin] [settings] [download] [upload] [coverart] [comment] [podcast] [stream] [jukebox] [share] \| New value: null
2021-11-02 10:38:59.224 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/AC DC/Dirty Deeds Done Dirt Cheap (1976)/01 - Dirty Deeds Done Dirt Cheap.flac \| EventType: CREATED \| Old value: null \| New value: Dirty Deeds Done Dirt Cheap
2021-11-02 10:38:59.351 WARN --- o.a.p.s.s.LastFMScrobbler : Failed to scrobble song 'Dirty Deeds Done Dirt Cheap' at Last.fm. Wrong username or password.
2021-11-02 10:38:59.933 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: ianb \| EventType: CREATED \| Old value: null \| New value: ianb [admin] [settings] [download] [upload] [coverart] [comment] [podcast] [stream] [jukebox] [share]
2021-11-02 10:39:01.261 INFO --- o.a.p.c.StreamController : 192.168.1.1: ianb listening to Disobey/(01) Officer Down - Bad Wolves.flac
2021-11-02 10:39:01.262 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves/Disobey/(01) Officer Down - Bad Wolves.flac \| EventType: REMOVED \| Old value: Officer Down \| New value: null
2021-11-02 10:39:01.263 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves/Disobey \| EventType: REMOVED \| Old value: Disobey \| New value: null
2021-11-02 10:39:01.273 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves/Disobey \| EventType: CREATED \| Old value: null \| New value: Disobey
2021-11-02 10:39:01.431 WARN --- o.a.p.s.s.LastFMScrobbler : Failed to scrobble song 'Officer Down' at Last.fm. Wrong username or password.
2021-11-02 10:39:02.182 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: ianb \| EventType: REMOVED \| Old value: ianb [admin] [settings] [download] [upload] [coverart] [comment] [podcast] [stream] [jukebox] [share] \| New value: null
2021-11-02 10:39:02.183 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /media/Bad Wolves/Disobey/(01) Officer Down - Bad Wolves.flac \| EventType: CREATED \| Old value: null \| New value: Officer Down
2021-11-02 10:39:02.183 INFO --- o.a.p.s.LoggingExceptionResolver : 192.168.1.1: Client unexpectedly closed connection while loading https://airsonic.ianburnip.space/stream?player=1&id=153831 (java.io.IOException: Broken pipe)
2021-11-02 10:39:02.327 WARN --- o.a.p.s.s.LastFMScrobbler : Failed to scrobble song 'Officer Down' at Last.fm. Wrong username or password.
2021-11-02 10:39:07.080 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: ianb \| EventType: CREATED \| Old value: null \| New value: ianb [admin] [settings] [download] [upload] [coverart] [comment] [podcast] [stream] [jukebox] [share]
111

```

### Steps to reproduce

Not sure I can legally share the files.

## System information

 * **Airsonic version**: *the version listed on the About page*
10.6.0.20200424173747

 * **Operating system**: *the operating system you're running Airsonic on.
   Linux, what distribution; Windows or Mac, what version?*

Airsonic on Unraid. Player on w10 Chrome

 * **Java version**: *the Java version you are using to run Airsonic.*
 * n/a*
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* None

 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*

Chrome & w10
 * **Language**: *which langauge/internationalization is in use*
English

**Comment by randomnicode** [comment]
Hi, you're running an old version of airsonic-advanced.

Might try switching to a more recent version and see if you still run into the same issues?
