### ISSUE TITLE
Import of exported DB to postgresql fails

### ISSUE THREAD

**Issue by nowheretobefound** [airsonic-advanced/airsonic-advanced#686]
When importing an exported database into an airsonic connected to postgresql I get this error:

2021-12-05 14:11:08.029 UTC [33] ERROR:  syntax error at or near "user" at character 13
db_1        | 2021-12-05 14:11:08.029 UTC [33] STATEMENT:  delete from user
airsonic_1  | 2021-12-05 14:11:08.037  INFO --- o.a.player.dao.DatabaseDao               : DB Import failed!
airsonic_1  | 
airsonic_1  | java.lang.RuntimeException: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: ERROR: syntax error at or near "user"
airsonic_1  |   Position: 13 [Failed SQL: (0) delete from user]
airsonic_1  |   at org.airsonic.player.util.LambdaUtils.lambda$1(LambdaUtils.java:53) ~[classes/:na]
airsonic_1  |   at org.airsonic.player.dao.DatabaseDao.importDB(DatabaseDao.java:27) ~[classes/:na]
airsonic_1  |   at org.airsonic.player.dao.DatabaseDao$$FastClassBySpringCGLIB$$8dcf3bd0.invoke(<generated>) ~[classes/:na]
airsonic_1  |   at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
airsonic_1  |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.8.jar:5.3.8]
airsonic_1  |   at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.8.jar:5.3.8]
airsonic_1  |   at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
airsonic_1  |   at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.8.jar:5.3.8]

running in docker and environmentvariable is set to :

- spring_liquibase_parameters_userTableQuote="

**Comment by randomnicode** [comment]
ahem, yeah this is a pretty special case, and we haven't thought of an automated solution for it yet. we're guessing the db that data was exported from was not postgres and did not have the usertablequote parameter set?

user is a reserved word in postgres.

you can try updating the export files manually to prepare for a postgres import. Here's how:
1. Export DB from any airsonic. It will be a zip file with a bunch of xml files inside.
2. Unzip, open each xml and replace all instances of `tableName="USER"` with `tableName="&quot;USER&quot;"`
3. Rezip and try importing that DB

**Comment by nowheretobefound** [comment]
thanks, I will try this out. The db is exported from hsql without usertablequote set.
Would it work to set the usertablequote on the hsql version and export again ?

**Comment by nowheretobefound** [comment]
Tried to quote the xml file, but it seems to crash even before loading data in the truncateAll part :

Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.DatabaseException: ERROR: syntax error at or near "user"
  Position: 13 [Failed SQL: (0) delete from user]
        at liquibase.command.CommandScope.execute(CommandScope.java:156) ~[liquibase-core-4.6.2.jar:na]
        at org.airsonic.player.service.DatabaseService.truncateAll(DatabaseService.java:229) ~[classes/:na]
        at org.airsonic.player.service.DatabaseService.runLiquibaseUpdate(DatabaseService.java:212) ~[classes/:na]
        at org.airsonic.player.service.DatabaseService.lambda$2(DatabaseService.java:161) ~[classes/:na]
        at org.airsonic.player.util.LambdaUtils.lambda$1(LambdaUtils.java:51) ~[classes/:na]

**Comment by randomnicode** [comment]
okay, we've moved the user table to users so we're not always fighting with postgres. So please do this:
- update both installations to the latest airsonic
- export from hsql again and import into postgres

**Comment by nowheretobefound** [comment]
thank you :)

**Comment by randomnicode** [comment]
did it work?

**Comment by nowheretobefound** [comment]
Eeeh, no :

Got this :

2021-12-07 20:29:22.084  INFO --- liquibase.changelog.ChangeSet            : New row inserted into PODCAST_EPISODE
2021-12-07 20:29:22.085  INFO --- liquibase.changelog.ChangeSet            : New row inserted into PODCAST_EPISODE
2021-12-07 20:29:22.085  INFO --- liquibase.changelog.ChangeSet            : New row inserted into PODCAST_EPISODE
2021-12-07 20:29:22.086  INFO --- liquibase.changelog.ChangeSet            : ChangeSet 5.xml::1638908343274-2::airsonic-data ran successfully in 10074ms
2021-12-07 20:29:22.144  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2021-12-07 20:29:22.153  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2021-12-07 20:29:22.208  INFO --- l.c.StandardChangeLogHistoryService      : Reading from public.databasechangelog
2021-12-07 20:29:22.230  INFO --- liquibase.changelog.ChangeSet            : New row inserted into MUSIC_FOLDER
2021-12-07 20:29:22.232  INFO --- liquibase.changelog.ChangeSet            : New row inserted into MUSIC_FOLDER
2021-12-07 20:29:22.232  INFO --- liquibase.changelog.ChangeSet            : ChangeSet 1.xml::1638908326791-1::airsonic-data ran successfully in 3ms
2021-12-07 20:29:22.240  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2021-12-07 20:29:22.248  INFO --- o.a.player.dao.DatabaseDao               : DB Import failed!

java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set 1.xml::1638908326791-2::airsonic-data:
     Reason: liquibase.exception.DatabaseException: ERROR: insert or update on table "music_folder_user" violates foreign key constraint "mfu_u_fk"
  Detail: Key (username)=(admin) is not present in table "users". [Failed SQL: (0) INSERT INTO public.MUSIC_FOLDER_USER (MUSIC_FOLDER_ID, USERNAME) VALUES (1, 'admin')]
        at org.airsonic.player.util.LambdaUtils.lambda$1(LambdaUtils.java:53) ~[classes/:na]
        at org.airsonic.player.dao.DatabaseDao.importDB(DatabaseDao.java:27) ~[classes/:na]
        at org.airsonic.player.dao.DatabaseDao$$FastClassBySpringCGLIB$$8dcf3bd0.invoke(<generated>) ~[classes/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.8.jar:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.8.jar:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.8.jar:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.8.jar:5.3.8]
        at org.airsonic.player.dao.DatabaseDao$$EnhancerBySpringCGLIB$$5b8c928e.importDB(<generated>) ~[classes/:na]
        at org.airsonic.player.service.DatabaseService.importDB(DatabaseService.java:203) ~[classes/:na]
        at org.airsonic.player.controller.DatabaseSettingsController.importDB(DatabaseSettingsController.java:97) ~[classes/:na]
        at org.airsonic.player.controller.UploadController.handleRequestInternal(UploadController.java:209) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]


On a clean postgres db. It seems to import the xml files in the wrong order, taking 5 and then 1, instead of 0,1,2,3 ....

**Comment by nowheretobefound** [comment]
Log from start of import :

2021-12-07 20:28:48.473  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: admin | EventType: CREATED | Old value: null | New value: admin ["JUKEBOX","COVERART","DOWNLOAD","PLAYLIST","ADMIN","STREAM","UPLOAD","SHARE","PODCAST","COMMENT","SETTINGS"]
2021-12-07 20:28:48.511  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: admin | EventType: CREATED | Old value: null | New value: org.airsonic.player.domain.UserSettings@444840cb
2021-12-07 20:28:48.817  INFO --- o.airsonic.player.dao.PlayerDao          : Created player 1
2021-12-07 20:28:48.957  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /var/music | EventType: CREATED | Old value: null | New value: music
2021-12-07 20:28:49.143 ERROR --- o.s.w.s.s.s.DefaultHandshakeHandler      : Handshake failed due to invalid Upgrade header: null
2021-12-07 20:29:05.228  INFO --- o.a.p.c.UploadController                 : Uploaded /var/airsonic/backups/airsonic.importDB.20211207202854/airsonic.exportDB.20211207201846.zip 
2021-12-07 20:29:05.228  INFO --- o.a.p.c.UploadController                 : Unzipping /var/airsonic/backups/airsonic.importDB.20211207202854/airsonic.exportDB.20211207201846.zip
2021-12-07 20:29:05.228  INFO --- o.a.p.c.UploadController                 : Trying zip-specific extraction method for /var/airsonic/backups/airsonic.importDB.20211207202854/airsonic.exportDB.20211207201846.zip
2021-12-07 20:29:05.323  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/5.xml
2021-12-07 20:29:05.324  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/1.xml
2021-12-07 20:29:05.324  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/3.xml
2021-12-07 20:29:05.324  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/0.xml
2021-12-07 20:29:05.325  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/7.xml
2021-12-07 20:29:05.470  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/2.xml
2021-12-07 20:29:05.471  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/6.xml
2021-12-07 20:29:05.489  INFO --- o.a.p.c.UploadController                 : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/4.xml
2021-12-07 20:29:05.512  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: admin | EventType: REMOVED | Old value: admin ["JUKEBOX","COVERART","DOWNLOAD","PLAYLIST","ADMIN","STREAM","UPLOAD","SHARE","PODCAST","COMMENT","SETTINGS"] | New value: null
2021-12-07 20:29:05.513  INFO --- o.a.p.service.DatabaseService            : DB unable to be backed up via these means
2021-12-07 20:29:05.713  INFO --- l.database.core.PostgresDatabase         : Set default schema name to public
2021-12-07 20:29:05.732  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2021-12-07 20:29:09.342  INFO --- l.c.StandardChangeLogHistoryService      : Reading from public.databasechangelog
2021-12-07 20:29:11.965  INFO --- liquibase.changelog.ChangeSet            : New row inserted into PODCAST_CHANNEL
2021-12-07 20:29:11.976  INFO --- liquibase.changelog.ChangeSet            : New row inserted into PODCAST_CHANNEL

**Comment by nowheretobefound** [comment]
I dont think Files.list(Path dir) gives any guarantees about sort order so the stream needs to hava an .sort(..) in DatabaseService

private void runLiquibaseUpdate(Connection connection, Path p) throws Exception {
        Database database = getDatabase(connection);
        truncateAll(database, connection);
        try (Stream<Path> files = Files.list(p)) {
            files.forEach(LambdaUtils.uncheckConsumer(f -> {
                Liquibase liquibase = new Liquibase(p.relativize(f).toString(), new FileSystemResourceAccessor(p.toFile()), database);
                liquibase.update(new Contexts());
            }));
        }
    } 

https://stackoverflow.com/questions/7199911/how-to-file-listfiles-in-alphabetical-order
