### ISSUE TITLE
Import of exported DB fails because of unsorted file order

### ISSUE THREAD

**Issue by nowheretobefound** [airsonic-advanced/airsonic-advanced#694]
Progressing from related issue #686 Latest release.

Trying to import an exported DB by uploading exported zip file

Got this :

2021-12-07 20:29:22.084 INFO --- liquibase.changelog.ChangeSet : New row inserted into PODCAST_EPISODE
2021-12-07 20:29:22.085 INFO --- liquibase.changelog.ChangeSet : New row inserted into PODCAST_EPISODE
2021-12-07 20:29:22.085 INFO --- liquibase.changelog.ChangeSet : New row inserted into PODCAST_EPISODE
2021-12-07 20:29:22.086 INFO --- liquibase.changelog.ChangeSet : ChangeSet 5.xml::1638908343274-2::airsonic-data ran successfully in 10074ms
2021-12-07 20:29:22.144 INFO --- l.l.StandardLockService : Successfully released change log lock
2021-12-07 20:29:22.153 INFO --- l.l.StandardLockService : Successfully acquired change log lock
2021-12-07 20:29:22.208 INFO --- l.c.StandardChangeLogHistoryService : Reading from public.databasechangelog
2021-12-07 20:29:22.230 INFO --- liquibase.changelog.ChangeSet : New row inserted into MUSIC_FOLDER
2021-12-07 20:29:22.232 INFO --- liquibase.changelog.ChangeSet : New row inserted into MUSIC_FOLDER
2021-12-07 20:29:22.232 INFO --- liquibase.changelog.ChangeSet : ChangeSet 1.xml::1638908326791-1::airsonic-data ran successfully in 3ms
2021-12-07 20:29:22.240 INFO --- l.l.StandardLockService : Successfully released change log lock
2021-12-07 20:29:22.248 INFO --- o.a.player.dao.DatabaseDao : DB Import failed!

java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set 1.xml::1638908326791-2::airsonic-data:
Reason: liquibase.exception.DatabaseException: ERROR: insert or update on table "music_folder_user" violates foreign key constraint "mfu_u_fk"
Detail: Key (username)=(admin) is not present in table "users". [Failed SQL: (0) INSERT INTO public.MUSIC_FOLDER_USER (MUSIC_FOLDER_ID, USERNAME) VALUES (1, 'admin')]
at org.airsonic.player.util.LambdaUtils.lambda$1(LambdaUtils.java:53) ~[classes/:na]
at org.airsonic.player.dao.DatabaseDao.importDB(DatabaseDao.java:27) ~[classes/:na]
at org.airsonic.player.dao.DatabaseDao$$FastClassBySpringCGLIB$$8dcf3bd0.invoke() ~[classes/:na]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.8.jar:5.3.8]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.8.jar:5.3.8]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.8.jar:5.3.8]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.8.jar:5.3.8]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar:5.3.8]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.8.jar:5.3.8]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.8.jar:5.3.8]
at org.airsonic.player.dao.DatabaseDao$$EnhancerBySpringCGLIB$$5b8c928e.importDB() ~[classes/:na]
at org.airsonic.player.service.DatabaseService.importDB(DatabaseService.java:203) ~[classes/:na]
at org.airsonic.player.controller.DatabaseSettingsController.importDB(DatabaseSettingsController.java:97) ~[classes/:na]
at org.airsonic.player.controller.UploadController.handleRequestInternal(UploadController.java:209) ~[classes/:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]

On a clean postgres db. It seems to import the xml files in the wrong order, taking 5 and then 1, instead of 0,1,2,3 ....

Log from start of import :

2021-12-07 20:28:48.473 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: admin | EventType: CREATED | Old value: null | New value: admin ["JUKEBOX","COVERART","DOWNLOAD","PLAYLIST","ADMIN","STREAM","UPLOAD","SHARE","PODCAST","COMMENT","SETTINGS"]
2021-12-07 20:28:48.511 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: admin | EventType: CREATED | Old value: null | New value: org.airsonic.player.domain.UserSettings@444840cb
2021-12-07 20:28:48.817 INFO --- o.airsonic.player.dao.PlayerDao : Created player 1
2021-12-07 20:28:48.957 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: /var/music | EventType: CREATED | Old value: null | New value: music
2021-12-07 20:28:49.143 ERROR --- o.s.w.s.s.s.DefaultHandshakeHandler : Handshake failed due to invalid Upgrade header: null
2021-12-07 20:29:05.228 INFO --- o.a.p.c.UploadController : Uploaded /var/airsonic/backups/airsonic.importDB.20211207202854/airsonic.exportDB.20211207201846.zip
2021-12-07 20:29:05.228 INFO --- o.a.p.c.UploadController : Unzipping /var/airsonic/backups/airsonic.importDB.20211207202854/airsonic.exportDB.20211207201846.zip
2021-12-07 20:29:05.228 INFO --- o.a.p.c.UploadController : Trying zip-specific extraction method for /var/airsonic/backups/airsonic.importDB.20211207202854/airsonic.exportDB.20211207201846.zip
2021-12-07 20:29:05.323 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/5.xml
2021-12-07 20:29:05.324 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/1.xml
2021-12-07 20:29:05.324 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/3.xml
2021-12-07 20:29:05.324 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/0.xml
2021-12-07 20:29:05.325 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/7.xml
2021-12-07 20:29:05.470 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/2.xml
2021-12-07 20:29:05.471 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/6.xml
2021-12-07 20:29:05.489 INFO --- o.a.p.c.UploadController : Processed /var/airsonic/backups/airsonic.importDB.20211207202854/4.xml
2021-12-07 20:29:05.512 INFO --- o.a.p.s.CacheConfiguration$CacheLogger : Cache Key: admin | EventType: REMOVED | Old value: admin ["JUKEBOX","COVERART","DOWNLOAD","PLAYLIST","ADMIN","STREAM","UPLOAD","SHARE","PODCAST","COMMENT","SETTINGS"] | New value: null
2021-12-07 20:29:05.513 INFO --- o.a.p.service.DatabaseService : DB unable to be backed up via these means
2021-12-07 20:29:05.713 INFO --- l.database.core.PostgresDatabase : Set default schema name to public
2021-12-07 20:29:05.732 INFO --- l.l.StandardLockService : Successfully acquired change log lock
2021-12-07 20:29:09.342 INFO --- l.c.StandardChangeLogHistoryService : Reading from public.databasechangelog
2021-12-07 20:29:11.965 INFO --- liquibase.changelog.ChangeSet : New row inserted into PODCAST_CHANNEL
2021-12-07 20:29:11.976 INFO --- liquibase.changelog.ChangeSet : New row inserted into PODCAST_CHANNEL

I dont think Files.list(Path dir) gives any guarantees about sort order so the stream needs to hava an .sorted(..) in DatabaseService

private void runLiquibaseUpdate(Connection connection, Path p) throws Exception {
Database database = getDatabase(connection);
truncateAll(database, connection);
try (Stream files = Files.list(p)) {
files.forEach(LambdaUtils.uncheckConsumer(f -> {
Liquibase liquibase = new Liquibase(p.relativize(f).toString(), new FileSystemResourceAccessor(p.toFile()), database);
liquibase.update(new Contexts());
}));
}
}

**Comment by nowheretobefound** [comment]
Success :+1:  Now running airsonic on postgres with all my data imported. Thank you
