### ISSUE TITLE
Exception when attempting to export database (legacy format)

### ISSUE THREAD

**Issue by Neurrone** [airsonic-advanced/airsonic-advanced#700]
## Problem description

I've just moved over to the Airsonic-advanced fork from Airsonic. I'm using whatever Airsonic's default database is for storing data (I believe its called Hsql?).

I wanted to try exporting the database in preparation for switching over to Postgres. The export failed with the following error.

```sh
BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed.                                                                                                                     
2021-12-11 22:34:26.879  INFO --- l.database.core.HsqlDatabase             : Set default schema name to PUBLIC                       
2021-12-11 22:34:27.105  INFO --- l.d.o.changelog.DiffToChangeLog          : changeSets count: 3                                     
2021-12-11 22:34:27.106  INFO --- l.d.o.changelog.DiffToChangeLog          : /var/airsonic/backups/airsonic.exportDB.20211211223426/0.xml does not exist, creating and adding 3 changesets.                                                                               
Generated changelog written to /var/airsonic/backups/airsonic.exportDB.20211211223426/0.xml                                          
BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed.                                                                                                                     
2021-12-11 22:34:27.450  INFO --- l.d.o.changelog.DiffToChangeLog          : changeSets count: 3                                     
2021-12-11 22:34:27.450  INFO --- l.d.o.changelog.DiffToChangeLog          : /var/airsonic/backups/airsonic.exportDB.20211211223426/1.xml does not exist, creating and adding 3 changesets.                                                                               
Generated changelog written to /var/airsonic/backups/airsonic.exportDB.20211211223426/1.xml                                          
BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed.                                                                                                                     
2021-12-11 22:34:28.791  INFO --- l.d.o.changelog.DiffToChangeLog          : changeSets count: 2                                     
2021-12-11 22:34:28.793  INFO --- l.d.o.changelog.DiffToChangeLog          : /var/airsonic/backups/airsonic.exportDB.20211211223426/2.xml does not exist, creating and adding 2 changesets.                                                                               
2021-12-11 22:34:46.955  INFO --- o.a.player.dao.DatabaseDao               : DB Export failed!                                       
                                                                                                                                     
java.lang.RuntimeException: liquibase.exception.LiquibaseException: liquibase.exception.CommandExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: liquibase.exception.UnexpectedLiquibaseException: Invalid string encoding on column.value. To resolve, remove the invalid character on the database and try again in changeSet /var/airsonic/backups/airsonic.exportDB.20211211223426/2.xml::1639233267526-1::airsonic-data. To resolve, remove the invalid character on the database and try again                      
        at org.airsonic.player.util.LambdaUtils.lambda$3(LambdaUtils.java:75) ~[classes/:na]                                         
        at org.airsonic.player.dao.DatabaseDao.exportDB(DatabaseDao.java:18) ~[classes/:na]                                          
        at org.airsonic.player.dao.DatabaseDao$$FastClassBySpringCGLIB$$8dcf3bd0.invoke(<generated>) ~[classes/:na]                  
```

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211209065629 – December 9, 2021 at 2:56:29 PM SGT [Commit: dd0d2af08363858d78d708a2d61af14793a79a05]
 * **Operating system**: Synology DS918+ DSM 7, running as a Docker image
 * **Java version**: Apache Tomcat/9.0.48, java 14.0.2, Linux (311.6 MB / 512.0 MB)
 * **Proxy server**: Traefik 2.5.5
 * **Client**: Firefox 95
 * **Language**: english

**Comment by randomnicode** [comment]
You have an character in the old db that has snuck in that is not in the charset

**Comment by Neurrone** [comment]
How do I either find out what that invalid character is, or convert my existing db into utf-8?

**Comment by randomnicode** [comment]
mind posting your db?

**Comment by Neurrone** [comment]
Can I email you the airsonic.script file separately?

**Comment by randomnicode** [comment]
zip up the entire db folder and you may email it to us

**Comment by Neurrone** [comment]
What's your email address?

**Comment by randomnicode** [comment]
randomnicode@gmail.com

**Comment by Neurrone** [comment]
Sent

**Comment by Neurrone** [comment]
@randomnicode thanks a lot for the help I got it to work.

Is there anything airsonic-advanced can do on its end, or this is something best solved by fixing the file?

**Comment by fsbruva** [comment]
@Neurrone or @randomnicode , Can either of you please share procedures/actions to resolve this? I am having the same problem. However, I'm on a headless server,  so I can't use the hsqldb 2.5 sqltool, because it REQUIRES X-windows.

**Comment by randomnicode** [comment]
@fsbruva bad encoding in the db. open it with a text editor and replace the bad characters accordingly. you can copy stuff then edit it if you/re headless

**Comment by dsiminiuk** [comment]
I have installed RazorSQL and loaded the database. I am able to export it, convert it, all without error. The exported file is 142,000 lines with the DDL and data inserts. Do I have to look for invalid characters in all text fields? Any tips to find invalid characters would be helpful.
