### ISSUE TITLE
Playback stops in the middle of a play list seemingly at random

### ISSUE THREAD

**Issue by khers** [airsonic-advanced/airsonic-advanced#717]
## Problem description

Seemingly at random the web player stops when there are remaining songs in the play list.  If I restart play on the next song things will continue from there.  Unfortunately, I haven't noticed possible other symptoms or correlated events.

### Steps to reproduce

Play an entire album.  Ocassionally, the player will stop after finishing a song in the middle of the list.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211208080314 – December 8, 2021 at 8:03:14 AM UTC [Commit: dc9c37c4611e17edfc6c1b830a7ccfbd567a2614]
 * **Operating system**: Ubuntu 18.04
 * **Java version**: openjdk 13.0.7 2021-04-20
 * **Proxy server**: Apache from Ubuntu 18.04
 * **Client**: Firefox
 * **Language**: en_US

**Comment by khers** [comment]
Here are all the logs from the start of playing the second song in an album (the player stopped after it finished).

```
2021-12-17 15:30:04.368  INFO --- o.a.p.c.StreamController                 : 168.122.212.173: user listening to Nothing New For Trash Like You/-that_way.mp3
2021-12-17 15:30:04.370  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/music/Against All Authority/Nothing New For Trash Like You | EventType: REMOVED | Old value: Nothing New For Trash Like You | New value: null
2021-12-17 15:30:04.441  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: user | EventType: REMOVED | Old value: user ["UPLOAD","ADMIN","COVERART","PODCAST","SHARE","COMMENT","SETTINGS","JUKEBOX","STREAM","DOWNLOAD"] | New value: null
2021-12-17 15:30:04.442  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/music/Against All Authority/Nothing New For Trash Like You/-that_way.mp3 | EventType: CREATED | Old value: null | New value: That Way
2021-12-17 15:30:04.447  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/music/Against All Authority/Nothing New For Trash Like You | EventType: CREATED | Old value: null | New value: Nothing New For Trash Like You
2021-12-17 15:30:04.447  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/This American Life/635.mp3 | EventType: EVICTED | Old value: 635: Chip in My Brain | New value: null
2021-12-17 15:32:14.439 ERROR --- o.s.w.s.s.s.DefaultHandshakeHandler      : Handshake failed due to invalid Upgrade header: null
2021-12-17 15:32:14.578  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/David Harvey's Anti-Capitalist Chronicles/ACCS03E12.mp3 | EventType: EXPIRED | Old value: Keynesianism of the 1960s | New value: null
2021-12-17 15:32:14.579  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/Bad Faith Premium Feed/1157.mp3 | EventType: CREATED | Old value: null | New value: Episode 132 - Solving The "Whiteness" Problem
2021-12-17 15:32:14.589  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/David Harvey's Anti-Capitalist Chronicles/ACCS03E12.mp3 | EventType: CREATED | Old value: null | New value: Keynesianism of the 1960s
2021-12-17 15:32:14.589  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/music/One Day As A Lion/One Day As A Lion EP/02 - Ocean View.mp3 | EventType: CREATED | Old value: null | New value: Ocean View
2021-12-17 15:32:14.590  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/But Why- A Podcast for Curious Kids/ButWhy_Squirrels_Ep166.mp3 | EventType: EVICTED | Old value: How do squirrels climb trees? | New value: null
2021-12-17 15:32:14.590  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/Bad Faith Premium Feed/156.mp3 | EventType: EVICTED | Old value: The Fight for $15 Isn't Over | New value: null
2021-12-17 15:32:14.591  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/music/Rihanna/Good Girl Gone Bad/01-Umbrella.mp3 | EventType: CREATED | Old value: null | New value: Umbrella
2021-12-17 15:32:14.591  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/Bad Faith Premium Feed/160.mp3 | EventType: EVICTED | Old value: Episode 56 -  The Bare Minimum | New value: null
2021-12-17 15:32:14.591  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/Marketplace/CAD9031961525.mp3 | EventType: EXPIRED | Old value: COVID-19 has made inflation a global problem | New value: null
2021-12-17 15:32:14.591  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: /home/airsonic/podcasts/Marketplace/CAD9031961525.mp3 | EventType: CREATED | Old value: null | New value: COVID-19 has made inflation a global problem
2021-12-17 15:33:01.811  INFO --- o.a.p.s.CacheConfiguration$CacheLogger   : Cache Key: user | EventType: CREATED | Old value: null | New value: user ["UPLOAD","ADMIN","COVERART","PODCAST","SHARE","COMMENT","SETTINGS","JUKEBOX","STREAM","DOWNLOAD"]
2021-12-17 15:33:11.354 ERROR --- o.a.p.s.LoggingExceptionResolver         : 127.0.0.1: An exception occurred while loading http://127.0.0.1:4040/websocket/720/4zzflzxx/xhr_streaming?t=<hidden>

org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class java.util.LinkedHashMap] with preset Content-Type 'application/javascript;charset=UTF-8'
        at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:312) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.HttpEntityMethodProcessor.handleReturnValue(HttpEntityMethodProcessor.java:219) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:78) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:124) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:517) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.8.jar!/:5.3.8]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) ~[jakarta.servlet-api-4.0.4.jar!/:4.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103) ~[spring-web-5.3.8.jar!/:5.3.8]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:578) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:517) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:392) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:257) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:352) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.core.AsyncContextImpl.setErrorState(AsyncContextImpl.java:440) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:166) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:241) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.48.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]

2021-12-17 15:33:11.355  WARN --- .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.http.converter.HttpMessageNotWritableException: No converter for [class java.util.LinkedHashMap] with preset Content-Type 'application/javascript;charset=UTF-8']

```

**Comment by randomnicode** [comment]
curious whether you have anything in bookmarks?

**Comment by khers** [comment]
Not for the song that was the last one to play before stopping

**Comment by modeckimellett** [comment]
I'm getting an issue which seems kind of related but is not quite as severe. Not sure if I should open a separate issue or not. Let me know!

### Description:
Tracks after the current track in the play queue do not play automatically if play is resumed from being paused for an extended period (5-10 minutes?). Sometimes playback is slow to restart from pause in this scenario as well.

### Steps to repeat:

1. Add an album to queue and play.
2. Pause for a while (5-10 minutes)
3. Click play button.

### Work arounds:
Clicking on the next item in the play queue works and the rest of the tracks play as normal.

### System Info:
**Airsonic**: 11.0.0-SNAPSHOT.20220124042650 – January 23, 2022 at 11:26:50 PM EST [Commit: [9c1a7ca71b1f1f5fbf25749175132e4076641072](https://github.com/airsonic-advanced/airsonic-advanced/commit/9c1a7ca71b1f1f5fbf25749175132e4076641072)] - linuxserver.io docker version
**Host System**
Raspberry Pi 4 - Raspbian 64 bit (no idea which version)
Running on LAN only connected via IP and http not https.
**Client System**
**OS**: Windows 10 Pro
**Browser**: Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by randomnicode** [comment]
What kind of files are these? mp3s? flacs?

Do you have bookmarks on?

**Comment by khers** [comment]
It has happened for me on both MP3 and FLAC files.

I do have Auto-Bookmarking enabled

**Comment by modeckimellett** [comment]
I haven't been using airsonic long enough to know what bookmarks are in this context. How would I check for that? I poked around the settings and googled but was unable to find it quickly. Working on other projects today but I can look tomorrow. The restarted song does start in the middle if that helps?

Most of my files are mp3s and flacs but I have a few weird ones in there as well. I believe that this happens consistently enough that I can say for sure it has happened with both of those file types.

**Comment by randomnicode** [comment]
Airsonic advanced saves the location where you paused a song or last left a song automatically if the "autobookmark" setting is checked in Settings. You can see these bookmarks in Bookmarks section.

When a bookmark happens, the next time you play the song, it continues from where it left off.
However, in order to do that, it has to skip forward in the file to the point where the bookmark is, which takes some time and may be the pauses you notice.

a look at the bookmarks section will inform you whether this is why things are happening. You can delete these bookmarks and turn off auto bookmarking and see if that fixes things.

**Comment by modeckimellett** [comment]
Ok so I found the bookmark settings in the Personal tab of settings (I only looked in General, Advanced, and Players when I was looking quickly previously). I will try unchecking this to see if it makes a difference. I do have 404 (this is almost definitely a coincidence??? lol) bookmarks in my bookmarks list currently.

However the pauses I am experiencing are not upon resuming play of the track but instead, after the paused track is resumed and completes, the following track never plays (and the player actually loses my place in the play queue). It is of course always possible that this will have some side effect which fixes my issue, but it doesn't seem to match up with what you are describing.

I generally do not use my airsonic instance on Mondays and Tuesdays. So we will see later in the week if anything changes. Thanks for your response!

**Comment by modeckimellett** [comment]
So it turns out that, for me, this is probably due to a Chrome bug for audio and video playback. I switched to Firefox and the problem went away. The description of the issue is for video only but I'm guessing that this also applies to audio based on my experience. I started seeing the same pausing behavior on Twitch and YouTube as well. Related Reddit thread: https://www.reddit.com/r/techsupport/comments/s263wg/video_pausing_by_itself_windows_10/
I had a link to Google's Chrome support ticket for the issue but it looks like they deleted the ticket.
