### ISSUE TITLE
Failed to create search index with null pointers and high CPU burn

### ISSUE THREAD

**Issue by PCOWandre** [airsonic-advanced/airsonic-advanced#726]
## Problem description

During an index update, there are a lot of errors about unable to create search index.

example:

``2021-12-31 03:01:38.580 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for Mechanical Bull``

### Steps to reproduce

Execute index update, watch the logs.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211220002741
 * **Operating system**: Solaris
 * **Java version**: 11.0.13
 * **Proxy server**: apache
 * **Client**: n/a
 * **Language**: English

## Additional notes

From catalina.out:
```
2021-12-31 03:01:38.580 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for Mechanical Bull

java.lang.NullPointerException: null
        at org.airsonic.player.service.search.IndexManager.index(IndexManager.java:137) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:311) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.lambda$22(MediaScannerService.java:316) ~[classes/:11.0.0-SNAPSHOT]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:411) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[na:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:316) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.lambda$22(MediaScannerService.java:316) ~[classes/:11.0.0-SNAPSHOT]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661) ~[na:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:316) ~[classes/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.lambda$22(MediaScannerService.java:316) ~[classes/:11.0.0-SNAPSHOT]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

```

**Comment by randomnicode** [comment]
is your index folder writable/readable?

should be in airsonic_home/index**

where the latest index is index19

**Comment by PCOWandre** [comment]
```
$ ls -ld /var/airsonic/index*
drwxr-xr-x   7 airsonic airsonic       7 Aug 28  2020 /var/airsonic/index18
drwxr-xr-x   7 airsonic airsonic       7 Sep  6 20:38 /var/airsonic/index19
```

Yep, And everything inside those directories is also owned by airsonic.

**Comment by pawtuxet** [comment]
I seem to be having the exact same issue, on a new installation in a Proxmox LXC unprivileged container.

Index folder /var/airsonic/index18 is created and populated during media scan but no media entries are created.
I've switched to a MySql backend, with a similar outcome - tables are created, but scanning media folders only results in a log file full of entries like the one listed above in Additional Notes.

/var/airsonic folder and entries are owned and writable by the user running Airsonic, and the same applies to the media folders.

- **Airsonic** version: Stable release 10.6.0
- **OS**: Ubuntu 21.10-standard
- **JRE**: openjdk-8-jre-headless 8u312-b07-0ubuntu1~21.10

**Comment by PCOWandre** [comment]
Further testing:

I ditched Tomcat and started standalone. Index built in seconds with no errors. I was using tomcat-8.5.73, so I'm going to try 9.0.48 to match the inbuilt tomcat and test again.

**Comment by PCOWandre** [comment]
OK, so I now have airsonic-advanced running again with no index errors.

I unpacked tomcat 9.0.56 and just copied `setenv.sh`, `context.xml` and `server.xml` straight over and fired it up by hand. Clean index build. Brought it up under SMF, errors everywhere. I suspect the problem is SMF isn't handing all the same environment variables as an interactive shell (e.g., `LANG`, `LC_ALL`). I updated `startup.sh` to export all those environment variables and got a clean index build.

I also suspect tomcat 8 would work fine with these environment variables set, but having done the upgrade now I don't see much reason to go back to 8. 

If `airsonic-advanced` decides to pull the documentation inhouse instead of pointing to the airsonic documentation, I'd be happy to add pull requests to polish up the tomcat deployment docs.

**Comment by poisonborz** [comment]
I'm having the same issue with Tomcat 9 in Proxmox LXC unprivileged container + Java 17.0.2 2022-01-18 LTS
After fresh install, and running the scanner for a while, Airsonic crashes, and cannot be restarted again.
In Catalina.out, I see huge amounts of error like this:

```
ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for <music>
java.lang.NullPointerException: Cannot invoke "org.apache.lucene.index.IndexWriter.updateDocument(org.apache.lucene.index.Term, java.lang.Iterable)" because the return value of "java.util.Map.get(Object)" is null
```

**Comment by awsms** [comment]
Having the same issue as OP after a reinstall of airsonic with a database cleanup

```
2022-03-05 22:18:04.904 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for Start_The_War

java.lang.NullPointerException: null
```

for basically 90% of my library

**Comment by awsms** [comment]
> OK, so I now have airsonic-advanced running again with no index errors.
> 
> I unpacked tomcat 9.0.56 and just copied `setenv.sh`, `context.xml` and `server.xml` straight over and fired it up by hand. Clean index build. Brought it up under SMF, errors everywhere. I suspect the problem is SMF isn't handing all the same environment variables as an interactive shell (e.g., `LANG`, `LC_ALL`). I updated `startup.sh` to export all those environment variables and got a clean index build.
> 
> I also suspect tomcat 8 would work fine with these environment variables set, but having done the upgrade now I don't see much reason to go back to 8.
> 
> If `airsonic-advanced` decides to pull the documentation inhouse instead of pointing to the airsonic documentation, I'd be happy to add pull requests to polish up the tomcat deployment docs.

So this is a webserver issue, not related to the db?

**Comment by PCOWandre** [comment]
Application server, not webserver. But this was not a database condition so much as a breakage caused by missing environment in my case. YMMV.

**Comment by awsms** [comment]
I just tried with the docker image. Funnily enough, I'm having the same issue but with random tracks. +80% of my library is accessible through the search
This seems like a consistent bug so I don't get how so few people reported having it

```
2022-03-06 15:19:51.093 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for music

org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:877) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:891) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1468) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1757) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.airsonic.player.service.search.IndexManager.index(IndexManager.java:137) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:309) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
```

**Comment by PCOWandre** [comment]
Your stacktrace looks substantially different to the one that I attached when I opened this issue. I'd suggest it should likely be opened as a new issue rather than added to this one as the root cause is probably going to be quite different.
