### ISSUE TITLE
Airsonic sonos integration returning access denied after months of working

### ISSUE THREAD

**Issue by augustf** [airsonic-advanced/airsonic-advanced#727]
## Problem description

After some months of working as expected with my Sonos system, Airsonic has begun returning "Login unauthorized," errors, preventing me from browsing or playing it via Sonos. The web interface continues to function as usual. 

I attempted to reauthorize Airsonic as a Sonos service, which created a second authorization code in the Airsonic UI, but I was still unable to browse or play from the library.

### Steps to reproduce

1. Link Airsonic to Sonos
2. Browse Airsonic Library from Sonos Controller apps
3. Airsonic shows access denied error and several exceptions (see below) are logged in the Airsonic log.

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20211028053855
 * **Operating system**: Linux Docker image
 * **Java version**: 14.0.2
 * **Proxy server**: None
 * **Client**: Sonos
 * **Language**: English

## Log output
`2021-12-31 20:04:28.273  WARN --- o.a.p.s.s.SonosFaultInterceptor : Error with Soap message                                                                                                                                                                                         
org.apache.cxf.interceptor.Fault: Login unauthorized                                               
        at org.apache.cxf.interceptor.AbstractFaultChainInitiatorObserver.onMessage(AbstractFaultCh
ainInitiatorObserver.java:75) ~[cxf-core-3.4.3.jar:3.4.3]                                          
        at org.apache.cxf.phase.PhaseInterceptorChain.wrapExceptionAsFault(PhaseInterceptorChain.ja
va:374) ~[cxf-core-3.4.3.jar:3.4.3]                                                                
        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:332) ~
[cxf-core-3.4.3.jar:3.4.3]                                                                         
        at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:
121) ~[cxf-core-3.4.3.jar:3.4.3]                                                                   
        at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.jav
a:265) ~[cxf-rt-transports-http-3.4.3.jar:3.4.3]                                                   
        at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.j
ava:234) ~[cxf-rt-transports-http-3.4.3.jar:3.4.3]                                                 
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208) ~[
cxf-rt-transports-http-3.4.3.jar:3.4.3]                                                            
        at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160) ~[
cxf-rt-transports-http-3.4.3.jar:3.4.3]                                                            
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embe
d-core-9.0.48.jar:9.0.48]                                                                          
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomca
t-embed-core-9.0.48.jar:9.0.48]                                                                    
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) 
~[tomcat-embed-core-9.0.48.jar:9.0.48]                                                             
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) ~[to
mcat-embed-core-9.0.48.jar:9.0.48]                                                                 
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat
-embed-core-9.0.48.jar:9.0.48]                                                                     
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]    
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]   
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tom
cat-embed-core-9.0.48.jar:9.0.48]                                                                  
at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]                                 
Caused by: org.airsonic.player.service.sonos.SonosSoapFault$LoginUnauthorized: Login unauthorized  
at org.airsonic.player.service.sonos.SonosLinkSecurityInterceptor.handleMessage(SonosLinkSe
curityInterceptor.java:137) ~[classes/:na]                                                         
at org.airsonic.player.service.sonos.SonosLinkSecurityInterceptor.handleMessage(SonosLinkSe
curityInterceptor.java:1) ~[classes/:na]                                                           
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308) ~
[cxf-core-3.4.3.jar:3.4.3]                                                                         
... 115 common frames omitted    `

**Comment by digitaldarragh** [comment]
I am encountering the same problem. Did you ever find a solution to this?

**Comment by pscriptos** [comment]
Unfortunately, I have exactly the same problem.

Have you found anything new on this topic or have you found a solution?

Thank you very much.

**Comment by swdwi2** [comment]
I too have this problem.  Help would be `appreciated.```
