### ISSUE TITLE
[Feature] Consider adopting an integration with the  OpenAPI spec of the PodcastIndex projrect. 

### ISSUE THREAD

**Issue by develroo** [airsonic-advanced/airsonic-advanced#734]
Simple request. Podcasts are becoming more centralised and it is becoming hard to find even an RSS stream sometimes depending on the service. Using the podcast index it is possible to have decentralised podcast distribution as well as many features not available to traditional podcast providers like Spotify or Apple.

Please investigate the documentation and consider adding this API to airsonic-advanced so podcasts can be sourced more reliably and to the benefit of consumers and creators and less for the middle men who monetise work. 

https://podcastindex-org.github.io/docs-api/#overview

**Comment by sv87411** [comment]
Hello,

I can see the Podcast Index settings and I've subscribed to Podcast index and have a username/password and API key. I've added a credential set for Podcast Index in AA.

There appears to be no "OK" or "Search" button to initiate the Podcast Index search that I an find.

How do you initiate a search from the Podcasts page in AA?

**Comment by randomnicode** [comment]
Your API Key is your username and your API Key Secret is your password for your credentials
1. Enable PodcastIndex in Settings -> Personal
2. Enter the creds as above in Settings -> Credentials for PODCAST_INDEX
3. Go to podcast channels and type in something for podcast index search bar
4. Press return

**Comment by randomnicode** [comment]
any logs?

**Comment by cocoonkid** [comment]
I tried again today and it worked now. Strange :)

Anyway how can I import OPML ?

**Comment by Fribb** [comment]
I don't know what I'm doing wrong here but this doesn't work for me. There is also absolutely no response from Airsonic on the WebUI in regards to any errors. The "Search" fails silently.

I registered on PodcastIndex and got the Email with my Login password, API Key and API secret.

As already stated in the Post here I enabled "Podcast search at Podcast Index" and added the Credentials to my User account. But none of the combinations works.

I tried using the Email I registered with and the login password I got in the Email -> doesn't work
I tried the API Key as the user and the Secret as Password -> doesn't work
I tried my Email with Secret -> doesn't work.

All I'm getting is a NullPointerException in the log

```
2022-04-20 16:06:58.981 WARN --- o.a.p.s.p.PodcastIndexService : Failed to execute PodcastIndex request: ResponseEntityProxy{[Content-Type: application/json,Chunked: true]}
2022-04-20 16:06:58.982 ERROR --- .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method
java.lang.NullPointerException: null
at org.airsonic.player.service.podcast.PodcastIndexService.search(PodcastIndexService.java:62) ~[classes/:na]
at org.airsonic.player.ajax.PodcastWSController.search(PodcastWSController.java:69) ~[classes/:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:569) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:524) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:458) ~[spring-messaging-5.3.18.jar:5.3.18]
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.18.jar:5.3.18]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by cocoonkid** [comment]
API Key as the user and the Secret as Password is what works for me. Saved in PLAINTEXT.

Make sure you don't have any accidental spaces or similar in there.  

Restart Airsonic thereafter.

**Comment by Fribb** [comment]
Got it, for whatever reason copying the secret always added a space in front of the actual copied text even though I only marked the secret. Thanks

**Comment by cocoonkid** [comment]
Excellent. There seems to be an "issue" with that space for lots of folks :-)

**Comment by develroo** [comment]
Sorry to be a dunce here. But is this included in the latest docker image? I just pulled 

`11.0.0-SNAPSHOT.20220418221611 – April 18, 2022 at 11:16:11 PM BST [Commit: [a5df18f2459362005a80af2903a6c5b23c8f194e](https://github.com/airsonic-advanced/airsonic-advanced/commit/a5df18f2459362005a80af2903a6c5b23c8f194e)]`

And I cannot see a podcast index setting anywhere? 

Is the docker image lagging? Or do I need to switch to another tag ?

**Comment by develroo** [comment]
Sad to say I am having issues setting up the Podcast Index account too. I know for a fact there are no errant spaces because I manually typed in the key so I am wondering what I am doing wrong? The encoder should be PLAIN, that that correct? Seems a bit odd to me but I did it. Restarted and I still get this in the logs
```


2022-05-14 16:05:09.547  WARN --- o.a.p.s.p.PodcastIndexService            : Failed to execute PodcastIndex request: ResponseEntityProxy{[Content-Type: application/json,Chunked: true]}
2022-05-14 16:05:09.552 ERROR --- .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method

java.lang.NullPointerException: null
	at org.airsonic.player.service.podcast.PodcastIndexService.search(PodcastIndexService.java:62) ~[classes/:na]
	at org.airsonic.player.ajax.PodcastWSController.search(PodcastWSController.java:69) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:569) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:524) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:458) ~[spring-messaging-5.3.18.jar:5.3.18]
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.18.jar:5.3.18]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```


How do I go about debugging the problem? I am almost sure it is not the credentials but if there is a way to look at the DB entry I can do a like for like comparison. 

Thanks for the feature, just hope I can get it to work ;)

**Comment by randomnicode** [comment]
The encoder for the password does not have to be plaintext. it can be anything that is decodable. Recommend AES for security.

If it's plaintext then you can compare it, it sits in the db in the user_credentials table..

As mentioned above: API Key as the user and the Secret as password.

Make sure you create an API Key from the Podcast Index website. The credentials you use to log in to the website won't work here.

**Comment by ElGordito** [comment]
I am having the exact same problem. Null pointer exception in log, nothing in UI.  I have followed the above exactly and even created a new key and secret and tried that.  I made sure there are no spaces.  Encrypted and clear, restarted.  Still cannot seem to make it work.  Any other troubleshooting suggestions?

**Comment by ElGordito** [comment]
Well, like many here.  I is now magically working. :-(
