### ISSUE TITLE
Airsonic fails to start due to database exception after migrating to the latest release

### ISSUE THREAD

**Issue by budgetfermium** [airsonic-advanced/airsonic-advanced#787]
## Problem description
After migrating from [Edge Release 11.0.0-SNAPSHOT.20220124042650](https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20220124042650) to [Edge Release 11.0.0-SNAPSHOT.20220203150207](https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20220203150207), Airsonic fails to start with a database exception error.
 
`Reason: liquibase.exception.DatabaseException: General error [Failed SQL: (-458) UPDATE PUBLIC.album SET cover_art_path = SUBSTR(cover_art_path, (SELECT LENGTH(music_folder.path) FROM music_folder WHERE music_folder.id = album.folder_id) + 1) WHERE cover_art_path IS NOT NULL]
2022-02-03 15:50:54.003 ERROR --- o.s.boot.SpringApplication               : Application run failed`

[Full log](https://github.com/airsonic-advanced/airsonic-advanced/files/7998265/log.txt)

### Steps to reproduce

1. Shut down Airsonic [Edge Release 11.0.0-SNAPSHOT.20220124042650](https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20220124042650)
2. Update to the latest release
3. Wait for migration to finish
4. Observe that Airsonic fails to start

## System information

 * **Airsonic version**: [Edge Release 11.0.0-SNAPSHOT.20220203150207](https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20220203150207)
 * **Operating system**: Ubuntu 20.04 (Using official docker image)
 * **Java version**: openjdk 14.0.2 2020-07-14
 * **Proxy server**: None
 * **Client**: None
 * **Language**: English

## Additional notes

I got exceptions when I attempted to export the database before the migration (reference #700).

**Comment by randomnicode** [comment]
likely something wrong with your db

**Comment by randomnicode** [comment]
can you execute the erroneous statement on your db manually?

**Comment by budgetfermium** [comment]
After running 
```
stmt.executeUpdate("UPDATE PUBLIC.album SET cover_art_path = SUBSTR(cover_art_path, (SELECT LENGTH(music_folder.path) FROM music_folder WHERE music_folder.id = album.folder_id) + 1) WHERE cover_art_path IS NOT NULL;"); 
```
I get
```
java.sql.SQLException: General error
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)

```

**Comment by randomnicode** [comment]
seems like an isue with your db, can you post it?

**Comment by randomnicode** [comment]
Try starting with a new db then

**Comment by johnmurrayvi** [comment]
I have the exact same issue. 
I've attached an example of the log output, the output from manually running the failing SQL statement, and a copy of the db it was run on.
[airsonic_db-20220409_163601.tar.gz](https://github.com/airsonic-advanced/airsonic-advanced/files/8457732/airsonic_db-20220409_163601.tar.gz)
[airsonic_migration_failure-manual_output.log](https://github.com/airsonic-advanced/airsonic-advanced/files/8457733/airsonic_migration_failure-manual_output.log)
[airsonic_migration_failure.log](https://github.com/airsonic-advanced/airsonic-advanced/files/8457734/airsonic_migration_failure.log)

**Comment by tarioch** [comment]
had a similar issue, in my case some of the paths were wrong before and did not contain the prefix it's trying to remove, this lead to the substring being larger than the actual string, I manually deleted those entries and then the migration worked

**Comment by ccandreva** [comment]
@tarioch I'm running into the same issue. Can you share how you found those entries and removed them ?

**Comment by tarioch** [comment]
I accessed the db with dbeaver (hsql embedded in my case) and then looked for the entries and cleaned them up.

**Comment by johnmurrayvi** [comment]
Took a little bit until I had some time to sit down and get mine fixed. It had something like 500 invalid entries... 

Perhaps these could be useful to others:
```sql
SELECT mf.id, mf.path, a.id, a.folder_id, a.path FROM album a JOIN music_folder mf ON a.path LIKE CONCAT(mf.path, '%') WHERE mf.id != a.folder_id
SELECT mf.id, mf.path, a.id, a.folder_id, a.path FROM album a JOIN music_folder mf ON a.path not LIKE CONCAT(mf.path, '%') WHERE mf.id = a.folder_id
```
The first should print info for an album that has a path that starts with a music folder's path, if the album's folder_id and the music folder's id are not the same. The second will print info for an album that has a folder_id that is equal to a music folder's id, but the album's path does not start with the music folder's path.

Watch out if you have library paths that could be a substring of another, like "/path/to/Music" and "/path/to/Music (New)" or something like that. This happened to me and you may want to use the following at first:
```sql
SELECT mf.id, mf.path a.id, a.folder_id, a.path FROM album a JOIN music_folder mf ON a.path LIKE CONCAT(mf.path, '/%') WHERE mf.id != a.folder_id
```
This is just like the first one above, except that it makes sure the next character in the album's path after the matching music folder path's substring is a '/', eliminating any issues with partially matching paths.

**Comment by jonknowsjon** [comment]
Apologies for necroposting this issue, but it seems related.

I'm working on migrating over from Subsonic v6 and was able to migrate to airsonic-advanced v10.6 without issue.  When I swap in the latest snapshot for v11 (20220625052932) I receive the same error as above.

Looking to dig into the database with dbeaver, I've tried using the hsqldb embedded 2.5.0 driver to open the database and but looks like an empty schema.   I've tried different hsqldb driver versions from maven to no avail either.

Is there some gotcha with regards to a database that's originally made by Subsonic, or maybe I'm missing something obvious?

**Comment by johnmurrayvi** [comment]
I think I used 2.5.4? It wasn't the latest version but it was later than
2.5.0.

Does it say it connects successfully?

**Comment by johnmurrayvi** [comment]
Sorry, I was wrong. Here are my driver settings:

![image](https://user-images.githubusercontent.com/619819/184153700-f4d6ed68-b766-47c0-b6ba-ab2defe1fdb5.png)

I had copied the database folder to my desktop, so my other settings were like this:
JDBC URL: "jdb:hsqldb:file:/home/user/Desktop/database_folder/airsonic"
Path: "/home/user/Desktop/database_folder/airsonic"
Username: "sa"
Password: empty

**Comment by jonknowsjon** [comment]
Those are the settings I have.   
jdbc url "jdbc:hsqldb:file:/home/jon/airsonicdb/db"
username sa / blank   driver is 2.5.0.

Just to test authentication I try a different username/password combo and authentication fails:
"invalid authorization specification - not found: foo" so I'm inclined to believe I have access to the database, but the schema is simply empty, something I have a hard time believing because the same DB when accessed by airsonic is throwing the above.  

I have no experience with these flat file databases, but is it possible there's a different schema?  Just viewing the files in a text editor, I can see the data, but when I open it using DBeaver, or even via the sqltool in the driver jar, I can view the PUBLIC.INFORMATION_SCHEMA.Tables, but there are no records.

I also tried copying the version from 10.6 and connecting to it using driver v1.8.0.10 and got similar results, and that database seems to be working fine. See below for examples,  note the expanded tables node and nothing underneath.
![Screenshot_20220811_170532](https://user-images.githubusercontent.com/74140555/184250952-6b93c20f-c0da-4eee-a7cf-6ea69a2a2617.png)

So I think the issue is either in my understanding of this database and how to connect to it, or perhaps a different schema?

**Comment by johnmurrayvi** [comment]
What's in the "db" folder at the end of your path?

If the "airsonic.{properties,script}" files are in there, you'll want your jdbc URL to be:
`jdbc:hsqldb:file:/home/jon/airsonicdb/db/airsonic`

You have to append the file name after the directory they're in to read it correctly.

**Comment by jonknowsjon** [comment]
That did the trick.   I know see that's exactly what you said before, but I missed.  Thank you!

**Comment by johnmurrayvi** [comment]
No problem, happy to help! That got me hung up at first too.
