### ISSUE TITLE
java.lang.Exception: Unsupported playlist

### ISSUE THREAD

**Issue by litebito** [airsonic-advanced/airsonic-advanced#821]
## Problem description
I just upgraded the standalone airsonic.war from a September snapshot to Edge Release 11.0.0-SNAPSHOT.20220213174344
I've an issue where playlists were imported fine when running the September snapshot, after the upgrade, they suddenly ALL cause the error
"java.lang.Exception: Unsupported playlist"

They are just standard m3u playlists
- they do have spaces in the name of the playlist

Example of the trace:

`
java.lang.Exception: Unsupported playlist Random 100 tracks from My A Collection.m3u
        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:342) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:385) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:330) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.lambda$14(PlaylistService.java:321) ~[classes!/:11.0.0-SNAPSHOT]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[na:na]
        at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:321) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:302) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:192) ~[classes!/:11.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
`

Sample of the content of the playlist:
..\..\Music\My A Collection\Bryan Adams\Bryan Adams - So Far So Good - Run To You.mp3
..\..\Music\My A Collection\Billy Joel\Billy Joel - Greatest Hits Volume III - I Go To Extremes.mp3
..\..\Music\My A Collection\Fine Young Cannibals\Fine Young Cannibals - The Raw And The Cooked - She Drives Me Crazy.mp3

### Steps to reproduce

- in Airsonic settings, go to "Media Folders"
- enable full media scan
- in the GUI, we I can see that the playlists are not updated with new music files, 
- in the log I see the exception errors

## System information

 * **Airsonic version**: Edge Release 11.0.0-SNAPSHOT.20220213174344
 * **Operating system**: Linux CentOS 7
 * **Java version**: 
openjdk version "11.0.14" 2022-01-18 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.14+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14+9-LTS, mixed mode, sharing)
Apache Tomcat/9.0.48, java 11.0.14, Linux (351.5 MB / 528.0 MB)
 * **Proxy server**:  None
 * **Client**: Chrome Version 98.0.4758.82 (Official Build) (64-bit)
 * **Language**: EN

**Comment by litebito** [comment]
Hi,
as requested, attached an example playlist
you have to rename the extension from txt back to m3u as I could not upload m3u files here
[(a) My A Collection test.txt](https://github.com/airsonic-advanced/airsonic-advanced/files/8148447/a.My.A.Collection.test.txt)

**Comment by randomnicode** [comment]
we cannot recreate this issue. The m3u file imports just fine (albeit obviously can't find any files)

**Comment by litebito** [comment]
> we cannot recreate this issue. The m3u file imports just fine (albeit obviously can't find any files)

I'll try to duplicate the VM I'm running Airsonic on and update airsonic again on the duplicate machine next weekend.
I'll let you know the outcome

**Comment by litebito** [comment]
The issue is back (I don't know since when exactly, I don't look in the logs that othen)
but the trace is different this time


```
2022-08-27 23:32:26.444  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /data/mstream_data/Other/_MusicPlaylists/Relaxing.m3u

java.lang.Exception: Unsupported playlist Relaxing.m3u
        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:342) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:385) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:330) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.lambda$0(PlaylistService.java:118) ~[classes!/:11.0.0-SNAPSHOT]
        at org.airsonic.player.service.PathWatcherService.lambda$2(PathWatcherService.java:56) ~[classes!/:11.0.0-SNAPSHOT]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

the content of the file still seems normal

**Comment by litebito** [comment]
Strange, after runnint through  the steps 5 times 
(steps are : Export playlists from Jriver to NAS, sync from NAS to Airsonic server, rescan media folders)
they are suddenly importing again
