### ISSUE TITLE
QA: Disabling Playlists

### ISSUE THREAD

**Issue by gerroon** [airsonic-advanced/airsonic-advanced#836]
Hi

I see that AA constantly throwing errors about importing playlists. I do not care about playlists. Is there a way to disable them? 

Also while it complains about playlists, the file themselves do not look like a playlist at all.

```
2022-02-26 13:16:20.496  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /var/playlists/music/Emanem (UK)/Coxhill, Lol & Weston, Veryan/Boundless (EMANEM 4021)/14 Slightly Tipsy Turvy.mp3



java.lang.Exception: Unsupported playlist 14 Slightly Tipsy Turvy.mp3

        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:342) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:385) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:330) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.lambda$14(PlaylistService.java:321) ~[classes/:na]

        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]

        at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[na:na]

        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:na]

        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]

        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]

        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]

        at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:321) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:302) ~[classes/:na]

        at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:192) ~[classes/:na]

        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]



2022-02-26 13:16:25.438  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /var/playlists/music/Emanem (UK)/Coxhill, Lol & Weston, Veryan/Boundless (EMANEM 4021)/15 Epilogue.mp3



java.lang.Exception: Unsupported playlist 15 Epilogue.mp3

        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:342) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:385) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:330) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.lambda$14(PlaylistService.java:321) ~[classes/:na]

        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
a
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]

        at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[na:na]

        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[na:na]

        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]

        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:na]

        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]

        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]

        at org.airsonic.player.service.PlaylistService.doImportPlaylists(PlaylistService.java:321) ~[classes/:na]

        at org.airsonic.player.service.PlaylistService.importPlaylists(PlaylistService.java:302) ~[classes/:na]

        at org.airsonic.player.service.MediaScannerService.lambda$3(MediaScannerService.java:192) ~[classes/:na]

        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]

        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]



```

**Comment by gerroon** [comment]
Thank you, you were right about the configuration. I changed it and I will test it now.

**Comment by randomnicode** [comment]
Can we close this issue?
