### ISSUE TITLE
Auto-Import of playlist fails

### ISSUE THREAD

**Issue by wolkenschieber** [airsonic-advanced/airsonic-advanced#852]
I'm running _Airsonic 11.0.0-SNAPSHOT.20220304165130_.

Directory `/playlists` is set to import the playlists from. The inital import seems to work fine. Airsonic lists everything in the Playlists view.

The playlist files are encoded with UTF-8: 
```
# file -i /playlists/Soundtrack.m3u 
Soundtrack.m3u: text/plain; charset=utf-8
```

However when a playlist file is changed, the import fails with an error.

Here's how I can reproduce the error:
1. Trigger auto-import by modifying file date: `# touch Soundtrack.m3u`
2. Airsonic logs will show following exception
```
2022-03-06 12:44:21.714  WARN --- o.a.p.service.PlaylistService            : Failed to auto-import playlist /playlists/Soundtrack.m3u
java.lang.Exception: Unsupported playlist Soundtrack.m3u
	at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:342) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.importPlaylistIfUpdated(PlaylistService.java:385) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.importPlaylist(PlaylistService.java:330) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PlaylistService.lambda$0(PlaylistService.java:118) ~[classes!/:11.0.0-SNAPSHOT]
	at org.airsonic.player.service.PathWatcherService.lambda$2(PathWatcherService.java:56) ~[classes!/:11.0.0-SNAPSHOT]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```

**Comment by wolkenschieber** [comment]
The playlist files are generated through [mkplylst](https://github.com/wolkenschieber/mkplylst). So the files should also have a BOM.

**Comment by wolkenschieber** [comment]
Issue #821 has a similar stacktrace.

**Comment by wolkenschieber** [comment]
This the playlist file mentioned in [comment #0](https://github.com/airsonic-advanced/airsonic-advanced/issues/852#issue-1160589598): [Soundtrack.tar.gz](https://github.com/airsonic-advanced/airsonic-advanced/files/8192555/Soundtrack.tar.gz)

**Comment by wolkenschieber** [comment]
I'm not sure, what triggers the error. Following steps allow me to reimport the playlists:
* Delete all playlists in Airsonic
* Shutdown Airsonic
* Delete playlist directory
* Create playlist directory
* Create playlists anew
* Start Airsonic
* Trigger Media scan
