### ISSUE TITLE
SQL Exception when cleaning up database, using external MySQL via JDBC

### ISSUE THREAD

**Issue by B16WLL** [airsonic-advanced/airsonic-advanced#871]
## Problem description

I'm using Airsonic Advanced with an external MySQL DB. Everything works perfectly, web interface, DSub connection,folders scan, music plays, artwork displays etc.
Except for cleaning up the database.

The settings page returns a 500 server error with the following information. Luckily the SQL command that's causing the issue is listed at the top of the trace

Status | 500
-- | --
Error | Internal Server Error
Message |  
Path | /musicFolderSettings.view
Time | Thu Mar 24 18:19:43 GMT 2022
Exception |  
Java version | Ubuntu 11.0.14
Operating system | Linux 5.15.0-23-generic
Server | Apache Tomcat/9.0.48
Memory | Used 160 of 206 MB
Stack trace | org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [delete from cover_art where entity_type='MEDIA_FILE' and entity_id in (select ca.entity_id from cover_art ca left join media_file m on ca.entity_id=m.id where m.id is null and ca.entity_type='MEDIA_FILE')]; SQL state [HY000]; error code [1093]; You can't specify target table 'cover_art' for update in FROM clause; nested exception is java.sql.SQLException: You can't specify target table 'cover_art' for update in FROM clause 	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1542) 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015) 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1025) 	at org.airsonic.player.dao.AbstractDao.update(AbstractDao.java:122) 	at org.airsonic.player.dao.CoverArtDao.expunge_aroundBody2(CoverArtDao.java:54) 	at org.airsonic.player.dao.CoverArtDao$AjcClosure3.run(CoverArtDao.java:1) 	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:67) 	at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:73) 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) 	at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:71) 	at org.airsonic.player.dao.CoverArtDao.expunge(CoverArtDao.java:53) 	at org.airsonic.player.dao.CoverArtDao$FastClassBySpringCGLIB$34bda47f.invoke(<generated>) 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) 	at org.airsonic.player.dao.CoverArtDao$EnhancerBySpringCGLIB$56c4ec43.expunge(<generated>) 	at org.airsonic.player.service.CoverArtService.expunge_aroundBody6(CoverArtService.java:103) 	at org.airsonic.player.service.CoverArtService$AjcClosure7.run(CoverArtService.java:1) 	at org.springframework.cache.aspectj.AbstractCacheAspect.ajc$around$org_springframework_cache_aspectj_AbstractCacheAspect$1$2bc714b5proceed(AbstractCacheAspect.aj:64) 	at org.springframework.cache.aspectj.AbstractCacheAspect$AbstractCacheAspect$1.invoke(AbstractCacheAspect.aj:71) 	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:366) 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:421) 	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:345) 	at org.springframework.cache.aspectj.AbstractCacheAspect.ajc$around$org_springframework_cache_aspectj_AbstractCacheAspect$1$2bc714b5(AbstractCacheAspect.aj:80) 	at org.airsonic.player.service.CoverArtService.expunge(CoverArtService.java:102) 	at org.airsonic.player.controller.MusicFolderSettingsController.expunge(MusicFolderSettingsController.java:141) 	at org.airsonic.player.controller.MusicFolderSettingsController.formBackingObject(MusicFolderSettingsController.java:100) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) 	at org.springframework.web.method.annotation.ModelFactory.invokeModelAttributeMethods(ModelFactory.java:143) 	at org.springframework.web.method.annotation.ModelFactory.initModel(ModelFactory.java:112) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:871) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1063) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.airsonic.player.security.JWTRequestParameterProcessingFilter.doFilter(JWTRequestParameterProcessingFilter.java:59) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.airsonic.player.filter.MetricsFilter.doFilter(MetricsFilter.java:30) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.airsonic.player.filter.RequestEncodingFilter.doFilter(RequestEncodingFilter.java:45) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.airsonic.player.filter.ParameterDecodingFilter.doFilter(ParameterDecodingFilter.java:57) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.airsonic.player.filter.BootstrapVerificationFilter.doFilter(BootstrapVerificationFilter.java:56) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:121) 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101) 	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218) 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:149) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:218) 	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:212) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.sql.SQLException: You can't specify target table 'cover_art' for update in FROM clause 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1348) 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025) 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) 	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) 	... 159 more

## System information

I'm using version 11.0.0-SNAPSHOT.20220320083637, but the problem also existed in earlier installs.
Ubuntu 21.04
Java:
openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-Ubuntu-0ubuntu2)
OpenJDK 64-Bit Server VM (build 11.0.14+9-Ubuntu-0ubuntu2, mixed mode, sharing)

MySQL
ver 8.0.28-0ubuntu4 (Ubuntu)

**Comment by B16WLL** [comment]
SQL isn't my strong point, but I think I've found the issue and _hopefully_ fixed it. 
Lines 54-56 in CoverArtDao.java contain the SQL with invalid commands.

The commands can be replaced with the following simplified versions, which I've tested on my own system using the MySQL console.

```
DELETE FROM cover_art WHERE entity_type='MEDIA_FILE' AND entity_id IN (SELECT media_file.id FROM media_file WHERE media_file.id IS NULL);
DELETE FROM cover_art WHERE entity_type='ALBUM' AND entity_id IN (SELECT album.id FROM album WHERE album.id IS NULL);
DELETE FROM cover_art WHERE entity_type='ARTIST' AND entity_id IN (SELECT artist.id FROM artist WHERE artist.id IS NULL);
```

They could be combined into one , but it does make reading it more tricky, and seemed to perform more slowly.

```
DELETE FROM cover_art WHERE (entity_type='MEDIA_FILE' AND entity_id IN (SELECT media_file.id FROM media_file WHERE media_file.id IS NULL)) OR (entity_type='ALBUM' AND entity_id IN (SELECT album.id FROM album WHERE album.id IS NULL)) OR (entity_type='ARTIST' AND entity_id IN (SELECT artist.id FROM artist WHERE artist.id IS NULL));
```

![screenshot](https://user-images.githubusercontent.com/102246595/161589677-5c0ccc46-ed55-4484-be76-ca5b2305fbd7.jpg)
Completely separate, but there's also a typo in line 56 (highlighted).

**Comment by randomnicode** [comment]
Mentioned in https://github.com/airsonic-advanced/airsonic-advanced/pull/880/files#r843519222 why this SQL is incorrect and not the fix to the issue
