### ISSUE TITLE
NullPointerException when parsing some podcast feeds

### ISSUE THREAD

**Issue by zhongkechen** [airsonic-advanced/airsonic-advanced#881]
## Problem description

When I added the following podcast feed https://raw.githubusercontent.com/numbbbbb/ggtalk-rss/master/rss.xml ,
the following exception was thrown when parsing it.

![image](https://user-images.githubusercontent.com/65260095/162630803-301f1c6c-130b-46b0-9264-3f47988ba8c0.png)

```
2022-04-09 18:06:13.613 WARN --- o.a.p.service.PodcastService : Failed to get/parse RSS file for Podcast channel https://raw.githubusercontent.com/numbbbbb/ggtalk-rss/master/rss.xml
--
 
java.lang.NullPointerException: null
at java.base/java.time.Instant.compareTo(Unknown Source) ~[na:na]
at java.base/java.time.Instant.compareTo(Unknown Source) ~[na:na]
at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Unknown Source) ~[na:na]
at java.base/java.util.Collections$ReverseComparator2.compare(Unknown Source) ~[na:na]
at java.base/java.util.TimSort.countRunAndMakeAscending(Unknown Source) ~[na:na]
at java.base/java.util.TimSort.sort(Unknown Source) ~[na:na]
at java.base/java.util.Arrays.parallelSort(Unknown Source) ~[na:na]
at java.base/java.util.stream.SortedOps$OfRef.opEvaluateParallel(Unknown Source) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.opEvaluateParallelLazy(Unknown Source) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(Unknown Source) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
at java.base/java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source) ~[na:na]
at org.airsonic.player.service.PodcastService.refreshEpisodes(PodcastService.java:561) ~[classes/:na]
at org.airsonic.player.service.PodcastService.doRefreshChannel(PodcastService.java:392) ~[classes/:na]
at org.airsonic.player.service.PodcastService.lambda$19(PodcastService.java:356) ~[classes/:na]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

```

It occurs to other Podcast feeds as well like https://rss.shawnxli.com/fanpie-film-ma or https://rss.shawnxli.com/fanpie-film-er

### Steps to reproduce

add one of the following feed to Podcast

- https://raw.githubusercontent.com/numbbbbb/ggtalk-rss/master/rss.xml 
- https://rss.shawnxli.com/fanpie-film-ma
- https://rss.shawnxli.com/fanpie-film-er

## System information

 * **Airsonic version**: 11.0.0-SNAPSHOT.20220404145227 – April 4, 2022 at 7:52:27 AM PDT [Commit: [8e97f9194d6f06518b1e03b7755e5134cc3edd7d](https://github.com/airsonic-advanced/airsonic-advanced/commit/8e97f9194d6f06518b1e03b7755e5134cc3edd7d)]
 * **Operating system**: Docker on Linux
 * **Java version**: Apache Tomcat/9.0.60, java 14.0.2, Linux (184.7 MB / 256.0 MB)
 * **Proxy server**: Nginx
 * **Client**: Brave Browser 1.37.111
 * **Language**: English

**Comment by dsmouse** [comment]
https://www.nasa.gov/rss/dyn/Houston-We-Have-a-Podcast.rss

**Comment by zhongkechen** [comment]
Still the same after upgrading to the latest 

```
airsonic-advanced    | 2022-07-05 17:58:30.524  WARN --- o.a.p.service.PodcastService             : Failed to get/parse RSS file for Podcast channel https://rss.shawnxli.com/fanpie-film-er
airsonic-advanced    |
airsonic-advanced    | java.lang.NullPointerException: null
airsonic-advanced    | 	at java.base/java.util.Comparator.lambda$comparing$77a9974f$1(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.Collections$ReverseComparator2.compare(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.TimSort.countRunAndMakeAscending(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.TimSort.sort(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.Arrays.parallelSort(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.stream.SortedOps$OfRef.opEvaluateParallel(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.stream.AbstractPipeline.opEvaluateParallelLazy(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.stream.AbstractPipeline.sourceSpliterator(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.stream.ReferencePipeline.forEachOrdered(Unknown Source) ~[na:na]
airsonic-advanced    | 	at org.airsonic.player.service.PodcastService.refreshEpisodes(PodcastService.java:561) ~[classes/:na]
airsonic-advanced    | 	at org.airsonic.player.service.PodcastService.doRefreshChannel(PodcastService.java:392) ~[classes/:na]
airsonic-advanced    | 	at org.airsonic.player.service.PodcastService.lambda$19(PodcastService.java:356) ~[classes/:na]
airsonic-advanced    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
airsonic-advanced    | 	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
airsonic-advanced    |
```
