### ISSUE TITLE
o.a.p.s.search.IndexManager Out of memory Crash

### ISSUE THREAD

**Issue by monik3r** [airsonic-advanced/airsonic-advanced#894]
Hey, after a few hours of running the server on the latest version I was getting some crashes. Looks like there may be a memory leak somewhere? This didn't happen in previous versions. I'm running the latest airsonic-advanced docker container (whichever memory limit is there will be what I'm running with now). Thanks, and let me know if I can help with debugging in any way. Here's a stacktrace (it happens multiple times before crashing):

```
2022-04-23 03:05:19.700 ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for songname

org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:877) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:891) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1468) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1757) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
	at org.airsonic.player.service.search.IndexManager.index(IndexManager.java:137) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:309) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by monik3r** [comment]
It seems as though reverting to airsonicadvanced/airsonic-advanced:gitrun-2090658641 keeps this issue from appearing, perhaps that can help with debugging

**Comment by watercrossing** [comment]
Hi @monik3r, I also get this error message and stack trace on a large chunk of my libary. I am using the latest airsonicadvanced/airsonic-advanced:latest docker image. Did you figure out how to solve this issue?

**Comment by monik3r** [comment]
I believe increasing the heap space worked here (the -Xmx flag)

**Comment by watercrossing** [comment]
Thanks @monik3r, but how do you actually change it without rebuilding the docker image? 
`-Xmx256m` is hardcoded in https://github.com/airsonic-advanced/airsonic-advanced/blob/89e6fe9aec80daf8224c6696f8f86bfcf22c6e0a/install/docker/run.sh#L23 and adding `-Xmx2048` to `JAVA_OPTS` in my docker-compose file doesn't fix the issue (and I am not sure how to test which of the two duplicate arguments is actually applied).

**Comment by watercrossing** [comment]
> and adding `-Xmx2048` to `JAVA_OPTS` in my docker-compose file doesn't fix the issue (and I am not sure how to test which of the two duplicate arguments is actually applied).

Nevermind, that did work, the log shows `Java: 14.0.2+12, OS: Linux, Memory (max bytes): 2147483648`.

Unfortunately the errors still occur for me:
```
ERROR --- o.a.p.s.search.IndexManager              : Failed to create search index for org.airsonic.player.domain.Album@7f3e2200

org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:877) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:891) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
        at org.apache.lucene.index.IndexWriter.updateDocuments(IndexWriter.java:1468) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1757) ~[lucene-core-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:50:37]
        at org.airsonic.player.service.search.IndexManager.index(IndexManager.java:116) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.updateAlbum(MediaScannerService.java:413) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:316) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.lambda$24(MediaScannerService.java:313) ~[classes/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) ~[na:na]
        at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:313) ~[classes/:na]
        at org.airsonic.player.service.MediaScannerService.lambda$6(MediaScannerService.java:219) ~[classes/:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
```
