### ISSUE TITLE
NullPointerException on nowPlaying.view

### ISSUE THREAD

**Issue by Dikakus** [airsonic-advanced/airsonic-advanced#898]
## Problem description

Airsonic throws a NullPointerException when accessing "Playing" menu option.

### Steps to reproduce

1. Play some album
2. Click on Playing menu option shows an exception and right panel (playing panel) is void.

![image](https://user-images.githubusercontent.com/14204887/165929773-3ee80eb0-4ed6-4c95-add3-458a01daf7e2.png)

  Log:

```
                        java.lang.NullPointerException
	at org.airsonic.player.service.SecurityService.isFileInFolder(SecurityService.java:433)
	at org.airsonic.player.service.SecurityService.lambda$11(SecurityService.java:420)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)

[...]
```

## System information

- Airsonic version: 11.0.0-SNAPSHOT.20220404145227 (2022/04/04)
- Operating system: Raspbian GNU/Linux bullseye, aarch64
- Java version: 11.0.14+9-post-Raspbian-1deb11u1
- Proxy server: None
- Client: Opera
- Language: Spanish

**Comment by mvn23** [comment]
Did you ever find a solution? I'm seeing the same.

**Comment by Dikakus** [comment]
> Did you ever find a solution? I'm seeing the same.

Hi. I switched to [airsonic-advanced](https://github.com/kagemomiji/airsonic-advanced) fork of @kagemomiji and works quite well.
