### ISSUE TITLE
Out of memory when moving to Airsonic-advanced from Airsonic

### ISSUE THREAD

**Issue by epross672** [airsonic-advanced/airsonic-advanced#903]
## Problem description

I am coming from Airsonic 10.6.2.  I replaced that airsonic.war with the airsonic advanced one and restarted Tomcat.  Wondering if someone can point me in the right direction.  I am using the default database but I am open to movign it to a network based MariaDB or other method if that would help.

### Steps to reproduce

I restart Tomcat and watch the log file and it eventually fails with a memory issue.

## System information

- Tomcat8
- Java 11.0.15
- Airsonic: 10.6.2
- Airsnic-advanced 10.6.0
- Rapsberry Pi:  Raspberry Pi 4 Model B Rev 1.1 running Bullseye

## Additional notes
```

2022-05-07 09:10:43.846  INFO --- org.airsonic.player.Application          : Starting Application v10.6.0 on subsonic with PID 468 (/var/lib/tomcat8/webapps/airsonic/WEB-INF/classes started by tomcat8 in /var/lib/tomcat8)
2022-05-07 09:10:43.858  INFO --- org.airsonic.player.Application          : The following profiles are active: legacy
2022-05-07 09:13:13.225  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2022-05-07 09:13:13.248  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2022-05-07 09:13:13.293  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2022-05-07 09:13:48.506  INFO --- l.executor.jvm.JdbcExecutor              : SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2022-05-07 09:13:48.517  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOG
2022-05-07 09:13:48.520  INFO --- l.c.StandardChangeLogHistoryService      : Reading from DATABASECHANGELOG
2022-05-07 09:13:48.523  INFO --- l.executor.jvm.JdbcExecutor              : SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2022-05-07 09:13:53.400  INFO --- l.c.visitor.RollbackVisitor              : Rolling Back Changeset:classpath:liquibase/10.6/timestamp-precision.xml::timestamp-precision::anon
2022-05-07 09:13:53.417  INFO --- l.c.visitor.RollbackVisitor              : Rolling Back Changeset:classpath:liquibase/10.6/user-credentials.xml::add-user-credentials::anon
2022-05-07 09:13:53.433  INFO --- l.c.visitor.RollbackVisitor              : Rolling Back Changeset:classpath:liquibase/10.6/expand-durations.xml::add-durations-to-playlist::anon
2022-05-07 09:13:53.466  INFO --- l.c.visitor.RollbackVisitor              : Rolling Back Changeset:classpath:liquibase/10.6/expand-durations.xml::add-durations-to-album::anon
2022-05-07 09:13:53.499  INFO --- l.c.visitor.RollbackVisitor              : Rolling Back Changeset:classpath:liquibase/10.6/expand-durations.xml::add-durations-to-mediafile::anon
2022-05-07 09:13:53.589  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2022-05-07 09:13:53.593  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2022-05-07 09:13:53.597  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2022-05-07 09:13:53.602  INFO --- l.executor.jvm.JdbcExecutor              : SELECT LOCKED FROM DATABASECHANGELOGLOCK WHERE ID=1
2022-05-07 09:13:53.614  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
2022-05-07 09:13:53.704  INFO --- l.executor.jvm.JdbcExecutor              : SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2022-05-07 09:13:53.710  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOG
2022-05-07 09:13:53.712  INFO --- l.c.StandardChangeLogHistoryService      : Reading from DATABASECHANGELOG
2022-05-07 09:13:53.714  INFO --- l.executor.jvm.JdbcExecutor              : SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2022-05-07 09:13:53.888  INFO --- l.executor.jvm.JdbcExecutor              : ALTER TABLE media_file ADD duration DOUBLE
2022-05-07 09:14:35.545 ERROR --- liquibase.changelog.ChangeSet            : Change Set classpath:liquibase/10.6/expand-durations.xml::add-durations-to-mediafile::anon failed.  Error: out of memory [Failed SQL: (72) ALTER TABLE media_file ADD duration DOUBLE]
2022-05-07 09:14:35.551  INFO --- l.l.StandardLockService                  : Successfully released change log lock
2022-05-07 09:14:35.555  WARN --- ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'themeSource': Unsatisfied dependency expressed through method 'setSettingsService' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'settingsService': Unsatisfied dependency expressed through field 'internetRadioDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internetRadioDao': Unsatisfied dependency expressed through field 'daoHelper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'daoHelper': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/airsonic/player/spring/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set classpath:liquibase/10.6/expand-durations.xml::add-durations-to-mediafile::anon:
     Reason: liquibase.exception.DatabaseException: out of memory [Failed SQL: (72) ALTER TABLE media_file ADD duration DOUBLE]
2022-05-07 09:14:35.646 ERROR --- o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'themeSource': Unsatisfied dependency expressed through method 'setSettingsService' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'settingsService': Unsatisfied dependency expressed through field 'internetRadioDao'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'internetRadioDao': Unsatisfied dependency expressed through field 'daoHelper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'daoHelper': Unsatisfied dependency expressed through field 'jdbcTemplate'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/airsonic/player/spring/DatabaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.MigrationFailedException: Migration failed for change set classpath:liquibase/10.6/expand-durations.xml::add-durations-to-mediafile::anon:
     Reason: liquibase.exception.DatabaseException: out of memory [Failed SQL: (72) ALTER TABLE media_file ADD duration DOUBLE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:723) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]


```

**Comment by yllekz** [comment]
FYI I tried that and it doesn't work.

This was how I added it to my docker-compose:
```
    environment:
      - JAVA_OPTS=-Xmx4096M #https://github.com/airsonic-advanced/airsonic-advanced/issues/903
```

It results in this:

```
Invalid maximum heap size: -Xmx4096M

The specified size exceeds the maximum representable size.

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.
```

**Comment by dsmouse** [comment]
> Invalid maximum heap size: -Xmx4096M

is that a 32bit OS or 32 bit Java process?  it could be 4096 is just too large a number... I'm spitballing here, but try 3072 instead

**Comment by yllekz** [comment]
32-bit OS. I adjusted it to 256 which let it run but it didn't fix the issue though.

**Comment by Abraka** [comment]
how big is you collection?
