### ISSUE TITLE
New disk same paths, podcast directory not accessible

### ISSUE THREAD

**Issue by undersound** [airsonic-advanced/airsonic-advanced#947]
## Problem description

I  just bought  a new ssd to have some more space for my music. Mounted it under the same path and copied everything over. Paths to my music and podcast directory are all the same.
When I start airsonic my music is found correctly only my podcast folder is giving below error message. I tried to add a new one (with a different name) and deleted the old one, cleaned up the database but unfortuanetely no luck. Any suggestions are appreciated....

```
java.lang.RuntimeException: The podcasts directory org.airsonic.player.domain.MusicFolder@22 isn't enabled or writeable.
at org.airsonic.player.service.PodcastService.createChannelDirectory(PodcastService.java:788) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PodcastService.doRefreshChannel(PodcastService.java:387) ~[classes!/:11.0.0-SNAPSHOT]
at org.airsonic.player.service.PodcastService.lambda$19(PodcastService.java:356) ~[classes!/:11.0.0-SNAPSHOT]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

## System information

11.0.0-SNAPSHOT.20220304165130 – March 4, 2022 at 5:51:30 PM CET [Commit: [bb5f4c74c5ffaa039aeb6953a19d9ff5221f701a](https://github.com/airsonic-advanced/airsonic-advanced/commit/bb5f4c74c5ffaa039aeb6953a19d9ff5221f701a)]
Linux Mint 21 
Apache Tomcat/9.0.48, java 11.0.16, Linux (112.2 MB / 250.0 MB)
Google Chrome  Version 105.0.5195.125 (Official Build) (64-bit)

**Comment by The-Exterminator** [comment]
Look on the first Line, is have not right permission

**Comment by undersound** [comment]
Thanks it was indeed a permission issue.
