### ISSUE TITLE
Media scan on NFS volume error: Value too large for defined data type

### ISSUE THREAD

**Issue by Alacika** [airsonic-advanced/airsonic-advanced#961]
## Problem description

Media scan on nfs volume does not work with the docker version of Airsonic. It works fine when run natively. I have tried with the existing database and config, and tried deleting everything and restarting with an empty config. The error is the same. The file system permissions are correct. I've tried user 1000:1000, and I've tried root 0:0 with uid/gid set, but the error is the same. Running it natively (not in docker) with the same settings, no error. Sorry for my poor English!

### Steps to reproduce

First run with empty config:

2022-11-28 18:12:30.546  WARN --- o.a.p.s.search.IndexManager              : /var/airsonic/index19/album_id3 does not exist. Please run a scan.
2022-11-28 18:12:30.545  WARN --- o.a.p.s.search.IndexManager              : /var/airsonic/index19/album does not exist. Please run a scan.
2022-11-28 18:12:30.544  WARN --- o.a.p.s.search.IndexManager              : /var/airsonic/index19/song does not exist. Please run a scan.
2022-11-28 18:12:30.564  WARN --- o.a.p.s.search.IndexManager              : /var/airsonic/index19/artist_id3 does not exist. Please run a scan.
2022-11-28 18:12:30.565  WARN --- o.a.p.s.search.IndexManager              : /var/airsonic/index19/artist does not exist. Please run a scan.
2022-11-28 18:12:30.569  INFO --- o.a.p.s.MediaScannerService              : Media library never scanned. Doing it now.
2022-11-28 18:12:30.588  INFO --- o.a.p.s.MediaScannerService              : Starting to scan media library.
2022-11-28 18:12:32.347 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.

java.io.UncheckedIOException: java.nio.file.FileSystemException: /var/music: Value too large for defined data type
	at java.base/java.nio.file.Files$2.hasNext(Unknown Source) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.trySplit(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
	at org.airsonic.player.service.MediaFileService.updateChildren(MediaFileService.java:418) ~[classes/:na]
	at org.airsonic.player.service.MediaFileService.getChildrenOf(MediaFileService.java:216) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.scanFile(MediaScannerService.java:312) ~[classes/:na]
	at org.airsonic.player.service.MediaScannerService.lambda$6(MediaScannerService.java:219) ~[classes/:na]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[na:na]
Caused by: java.nio.file.FileSystemException: /var/music: Value too large for defined data type
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.UnixException.asIOException(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.readNextEntry(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.UnixDirectoryStream$UnixDirectoryIterator.hasNext(Unknown Source) ~[na:na]
	... 24 common frames omitted

## System information

 * **Airsonic version**: *the version listed on the About page*
 Latest version on DockerHub (https://hub.docker.com/r/airsonicadvanced/airsonic-advanced - Updated 5 months ago)
 * **Operating system**: *the operating system you're running Airsonic on.
   Linux, Raspbian Buster on Raspberry PI4 8GB version
 * **Java version**: *the Java version you are using to run Airsonic.*
 Java 14.0.2 (Airsonic Docker enviroment) 
 * **Proxy server**: *if running Airsonic behind a proxy, what server and
   version? Otherwise,* None
None
 * **Client**: *what browser and version you use to access the Airsonic web
   interface, or the name and version of another app you're using.*
 Google Chrome 107.0.5304.121
 * **Language**: *which langauge/internationalization is in use*
English
## Additional notes

*Include any extra notes here. Otherwise you may remove this section.*

**Comment by Alacika** [comment]
I continued the investigation on Raspberry3 and Raspberry4 devices, in a Docker environment, on the Raspbian operating system. The scan error only occurred on the 32-bit Raspbian, it worked flawlessly on the 64-bit system. So the error can be related to the 32-bit system.
